### ISSUE TITLE
TFileOpenDialog Does Not Style Correctly 

### ISSUE THREAD

**Issue by zekiguven** [RRUZ/vcl-styles-utils#120]
When i use TFileOpenDialog component.
its does not style correctly.  
I use Win 8.1 and Delphi XE3.

**Comment by RRUZ** [comment]
Sorry but the New dialogs (introduced in Windows Vista) are not supported by the library. If you want style the open file dialog, you must use the *TOpenDialog* component instead. For more info about this feature check this https://github.com/RRUZ/vcl-styles-utils/wiki/VclStylesSysControls

**Comment by RRUZ** [comment]
The new version of the library now supports the new common dialogs https://theroadtodelphi.wordpress.com/2015/07/13/vcl-styles-utils-now-supports-the-new-common-dialogs/
