### ISSUE TITLE
Drawing problem on large popup menu.

### ISSUE THREAD

**Issue by zekiguven** [RRUZ/vcl-styles-utils#121]
Drawing problem on large popup menu. 
An Arrow end of the menu not showed, and scroll drawing problem exists.

Sample code: 
procedure TForm1.Button1Click(Sender: TObject);
var
  mi:TMenuItem;
  I: Integer;
begin
  for I := 0 to 100 do
  begin
    mi:=TMenuItem.Create(PopupMenu1);
    mi.Caption:='Item '+IntToStr(I);
    PopupMenu1.Items.Add(mi);
  end;

end;

![menuerror](https://cloud.githubusercontent.com/assets/628837/7744907/c5c27d6e-ffaf-11e4-83dc-a914e710afc4.png)

**Comment by vandrovnik** [comment]
The same problem happens with MainMenu.

**Comment by obones** [comment]
Hello,

Just a few elements following the research I did in this matter as I developed the painters inside the JVCL which achieve a bit of the same, without styles:

The `GetMenuItemRect`function does not take into account the scrolling that may have occurred in the menu, meaning that item 0 is always said to be at the top left, which is not correct once scrolled.

The popup menu remembers its scroll state between appearances.

The `MN_BUTTONDOWN` event can get the following undocumented item indexes:  

    SCROLL_UP_BUTTON_INDEX = UINT(-3);
    SCROLL_DOWN_BUTTON_INDEX = UINT(-4);

This would be convenient to store an offset into the list. However, when styled, the menu does not seem to contain the up button, I never get it, while I do get the down button. 

When not using a theme but using owner drawing (which is what the JVCL is doing), the buttons are properly displayed and the coordinates inside `DRAWITEMSTRUCT`for the `WM_DRAWITEM` message are valid and respect the scrolling if there was one.

I tried activating owner drawing while using a theme, but the `WM_DRAWITEM` messages were no longer received, it seems they are intercepted somewhere (or not even sent)

I'd really love to see this issue fixed and I hope this helps a bit. But for now, I'm a bit stuck without a solution.

**Comment by jsweby** [comment]
I am also experiencing the random lines appearing on long menus, as in the screenshot above.

**Comment by gandf** [comment]
Commit [d732338f2e23928adf1c1ebc97c314ae49019cee](https://github.com/RRUZ/vcl-styles-utils/pull/207/commits/d732338f2e23928adf1c1ebc97c314ae49019cee) hould partially fix this issue.
Up and down button not fixed.

**Comment by gandf** [comment]
Commit [629456cccc6f9a0935eb40da165b9ddd529c50e6](https://github.com/RRUZ/vcl-styles-utils/pull/207/commits/629456cccc6f9a0935eb40da165b9ddd529c50e6) fix this issue.

**Comment by RRUZ** [comment]
This issue was fixed in the last commit.
