### ISSUE TITLE
Vcl.Styles.NC Cannot work on 64 bit programs

### ISSUE THREAD

**Issue by awenewa** [RRUZ/vcl-styles-utils#122]
![20150603121201](https://cloud.githubusercontent.com/assets/8545123/7952551/bd6aa440-09e9-11e5-8ffa-09982906ade1.jpg)

**Comment by RRUZ** [comment]
Thanks for the report , the issue was fixed in the current commit.

**Comment by awenewa** [comment]
Thanks for all of your hard work.
