### ISSUE TITLE
Access violation when open context menu inside TOpenDialog and other dialogs

### ISSUE THREAD

**Issue by cleberlr** [RRUZ/vcl-styles-utils#125]
in file: vcl.styles.utils.menus 

in procedure TSysPopupStyleHook.DrawItem

change (starts in line 540):
```
  if (LParentMenu <> nil) and (LParentMenu.OwnerDraw) and (@LMenuItem.OnDrawItem <> nil) then
  begin
    LMenuItem.OnDrawItem(LMenuItem, Canvas, ItemRect, (isHot in State));
    Exit;
  end;

  if (LParentMenu <> nil) and (LParentMenu.OwnerDraw) and (LMenuItem <> nil) and (@LMenuItem.OnAdvancedDrawItem <> nil) then
  begin
    LOwnerDrawState := [];

    if isHot in State then
      Include(LOwnerDrawState, odSelected);
    if isDisabled in State then
      Include(LOwnerDrawState, odDisabled);
    if isChecked in State then
      Include(LOwnerDrawState, odChecked);
    if isDefault in State then
      Include(LOwnerDrawState, odDefault);

    LMenuItem.OnAdvancedDrawItem(LMenuItem, Canvas, ItemRect, LOwnerDrawState);
    Exit;
  end;
```

change to:

```
  if (LParentMenu <> nil) then
  begin
    if (LParentMenu.OwnerDraw) and (@LMenuItem.OnDrawItem <> nil) then
    begin
      LMenuItem.OnDrawItem(LMenuItem, Canvas, ItemRect, (isHot in State));
      Exit;
    end;
  end;

  if (LParentMenu <> nil) then
  begin
    if (LParentMenu.OwnerDraw) and (LMenuItem <> nil) and (@LMenuItem.OnAdvancedDrawItem <> nil) then
    begin
      LOwnerDrawState := [];

      if isHot in State then
        Include(LOwnerDrawState, odSelected);
      if isDisabled in State then
        Include(LOwnerDrawState, odDisabled);
      if isChecked in State then
        Include(LOwnerDrawState, odChecked);
      if isDefault in State then
        Include(LOwnerDrawState, odDefault);

      LMenuItem.OnAdvancedDrawItem(LMenuItem, Canvas, ItemRect, LOwnerDrawState);
      Exit;
    end;
  end;
```

**Comment by RRUZ** [comment]
Hi, I can't reproduce the issue (the access violation), can you please attach a sample project?

**Comment by cleberlr** [comment]
I'm trying to reproduce the problem in a simple project, but I still didn't get.. My program with this bug has more than 30k lines. I'm using ClearType quality render fonts and main and popup menu  (with disable and hidden menu items) are using owner draw and the program access OLE controls too, but this problem occur before access OLE. I will try to discover in which situation occur this access violation

**Comment by RRUZ** [comment]
Hi, Any news about this?

**Comment by cleberlr** [comment]
Hi Rodrigo. I was travelling..
I discover that the problem is caused by a plugin of web browser installed
by the bank for access internet bank...
It´s not a bug of vcl-styles-utils, but access violation happens in VCL
styles operations and this plugin...

It´s a random access violation...

thanks for your interest.. If I have more information I will post in yor
site.

Cleber

Hi, Any news about this?

—
Reply to this email directly or view it on GitHub
<https://github.com/RRUZ/vcl-styles-utils/issues/125#issuecomment-164983217>
.
