### ISSUE TITLE
which component do you use?thank you!

### ISSUE THREAD

**Issue by chineselzh** [RRUZ/vcl-styles-utils#128]
Excuse me,can you tell me which component do you use on the Picture？
and which style of it?
thank you very much !
jam  ShellBrowser or else ?
see the picture please.
![](http://i.imgur.com/gIWPh9k.png)
![pic](http://7xii3z.com1.z0.glb.clouddn.com/QQ20150716163555.png)

**Comment by RRUZ** [comment]
This is just a *TOpenDialog* on Windows 10, with the  *glow* Vcl Style using the *Vcl Styles Utils*. You can find more info here .https://theroadtodelphi.wordpress.com/2015/07/13/vcl-styles-utils-now-supports-the-new-common-dialogs/

**Comment by chineselzh** [comment]
OK,thank you very much !
