### ISSUE TITLE
Progressbar eOutOfRessources

### ISSUE THREAD

**Issue by rschroedter** [RRUZ/vcl-styles-utils#129]
Hi,

the styling of the TProgressbar raises an exception eOutOfRessources when the progressbar.max is set equal 0.

To reproduce:
- New Project;
- drop a Tprogressbar and a TButton on the form
- TButtonPressed method: Progressbar.max := 0

exception will be raised while theming is active.

Using Delphi xe5 latest vcl.styles.

Exception is only raised when compiler directive HOOK_TProgressBar is defined;

**Comment by RRUZ** [comment]
The issue was fixed, please try with the new version. Thanks for the report.
