### ISSUE TITLE
Style TRichEdit and TJvRichEdit?

### ISSUE THREAD

**Issue by PeterPanino** [RRUZ/vcl-styles-utils#130]
Is it possible to style TRichEdit and TJvRichEdit? Both do not work well with standard VCL Styles, e.g. Amakrits VCL style.

**Comment by RRUZ** [comment]
Can you provide more details ? a screenshot , Delphi Version.

**Comment by PeterPanino** [comment]
Please see here:
    
    
    
    Kind regards,
    Peter Aschbacher
    PA-Soft
    https://www.pa-soft.com
    
    Am 29.07.2015 um 17:59 schrieb Rodrigo
      Ruz:
    
    
      Can you provide more details ? a screenshot , Delphi Version.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by RRUZ** [comment]
The purpose for the TRichEdit  Style hook is only apply the style to the border, scrollbars and background of the control. If you want change the color of the text of the RichEdit control you must use the `SelAttributes.Color` property. About the third-party implementations of the RichEdit like the `TJvRichEdit` you must ask to the maintainers of such components.
