### ISSUE TITLE
NCControl menu location

### ISSUE THREAD

**Issue by bdwilton** [RRUZ/vcl-styles-utils#131]
Hey RRuz,
Just been having a quick look at the demo's and was wondering if the NCControl has the ability to right alight the buttons.

For example show the Menu icon left side, then title and have the buttons you add to the list aligned to the right hand side (or added to the right hand side) ?

Title would get clipped to the area available.

Nice work by the way.

**Comment by RRUZ** [comment]
Hi, for the moment the NC Controls can't be aligned to the right, I expect add such feature in a future version.
