### ISSUE TITLE
TVclStylesSystemMenu

### ISSUE THREAD

**Issue by Bononi** [RRUZ/vcl-styles-utils#132]
Hi Rodrigo.

I'm using your library for a while and I think it's great and I'm always looking foward your improvements. Thanks for helping us developing apps with Delphi.
I'm not sure that it's exactly an issue, I think it is more like a couple of suggestions.
1 - I think it would be great if you manage to publish the caption in the menu, in order to enable the programmer changed it within the implementation instead of changing it in the vcl unit. That would be useful for non-english users.
2 - Before you create the TVclStylesSystemMenu object, I made a custom menu similar to it using a jvcl component and a routine for loading the styles. It was working fine but I discovered that if you use NC controls and choose the "windows" vanilla style you get an exception error message and the controls disappear from the NC area. So I changed the routine to not include the "windows" style. I'm not sure how do you plan to solve/fix this but I'm fine with not having an option for the windows style.

Best regards

**Comment by RRUZ** [comment]
I just added the MenuCaption property to TVclStylesSystemMenu component
 About your second question,  the TNCControls only works when the VCL Styles are enabled.
