### ISSUE TITLE
Appearance of TDateTimePicker

### ISSUE THREAD

**Issue by BavDev** [RRUZ/vcl-styles-utils#133]
With many styles, the TDateTimePicker button looks silly. F.ex. with Iceberg Classico the button has a calendar icon but it looks quite ugly. A nice appearance would be like this: the button is completely inside the edit field and the frame around the edit field is around the button. Rodrigo has shown that this works with some newer XE8 style but not with most other styles. Or maybe only with DXE versions prior to 8? There the button still covers the frame border of the edit field which looks not professional. Another example is the Metro style. Green looks nice while with Black and Blue the icon disappears when you move the mouse over it. 
And finally, if you use the long date format, the button has no icon and looks ugly. You can see both in the hooks demo app below each other. See the screenshot for Iceberg Classico:

![tdtp_iceberg](https://cloud.githubusercontent.com/assets/13589360/9009488/d29d106a-37a1-11e5-8c70-4054305c4c81.png)

**Comment by RRUZ** [comment]
Hi just fixed this issue in the last version.

**Comment by BavDev** [comment]
Hello Rodrigo.

I think this is not good enough.

![tdtp_iceberg_2](https://cloud.githubusercontent.com/assets/13589360/9037193/0302f000-39e9-11e5-9389-142dc1eeac22.png)

1) The Button of the long format is too far right. I have copied in a screenshot with hovered button, there you see that.
2) The button with the calendar does not change its colour when hovering or clicking on it. I believe it must behave with the same colours like normal buttons or the dropdown button of the long format.
3) Still I believe that the calendar button must be INSIDE the edit field, not besides it. Even if it should be besides, then there must not be that beveled line inbetween but a single line only. This is similar to many styles I tested, like you see it with Iceberg in the screenshot. I understand that this icon which you are using here does not fit, but why are you using it? From where does it come? For sure not from the style image. I believe the original Windows calendar icon would look much more better in many Win7-like styles like Iceberg, Lavender, etc.

Finally I believe that you will have to reintroduce the special TDateTimePicker hook in order to fix that all?

Best regards
Stephan

**Comment by RRUZ** [comment]
My answers goes below 

1. The *Rect* used to draw the *dropdown* button is given by the system itself, Also the image depends of the selected VCL Style. So there is not much room to modifications here. 

2. The hover Color changes only in some Styles depending if the *clHighlight* color is visible over the *clWindow* color (you can test with another styles).

3. The image for the calendar is used from a internal font used by the library. Is not possible use the original Native Themed Calendar image because doesn't look good with some dark styles.  

 The *TDateTimePicker* can't be full customized using a Style hook, instead a hook in the *Uxtheme* is used.

**Comment by BavDev** [comment]
1) From my opinion, the Rect is smaller than in normal listbox, but this is not the case in original Windows theme. There they are the same size. Shouldn't the button look exactly like the one for normal listboxes?
2) As I told you, I would expect that there are the same colours like for every button or the dropdown button. This is the case with the original Windows, isn't it? So styled apps should behave the same way?
3) My proposal was to use the original icon for such themes where it looks good, and of course the one you are using is good for those darker themes. Well, dark themes are not suitable for business apps, but this is another topic...

Well, if I will have time, then I will write my own hook...
