### ISSUE TITLE
mainmenu Disappeared

### ISSUE THREAD

**Issue by mazluta** [RRUZ/vcl-styles-utils#134]
i dont now if isit the right palce, sorry if not.

but when i disable or unvisuble item from the main menu, the all main menu Disappeared

a specially if i disable groupitem entry.

how do i force the mainmenu to repaint?

Yossi

**Comment by RRUZ** [comment]
Hi, please attach a sample Delphi project to reproduce the issue.

**Comment by mazluta** [comment]
try with styles and without styles

http://www.hanibaal.co.il/DocIL/MzDocIL.zip

u can contact me via mazluta@hanibaal.co.il

thanks

**Comment by mazluta** [comment]
in the EnabledUserButton procedure there are 3 line that make the problems

  //START menu dont show
  mnuDocuments.Enabled         := False;
  mnuMaintenence.Enabled       := False;
  mnuTables.Enabled            := False;

if u disabled those lines all work fine.

**Comment by RRUZ** [comment]
You can try forcing the form update like so (you must do this in the *finally* part of the  *FormActivate* method). 


```delphi
  Finally
    if ErrorOnActive then
    begin
      mnuMaintenence.Visible := True;
      mnuMaintenence.Enabled := True;
    end;

    if Self.HandleAllocated and not IsIconic(Self.WindowHandle) then
      SetWindowPos(Self.WindowHandle, 0, Self.Left, Self.Top, Self.Width+1, Self.Height,
        SWP_NOZORDER + SWP_NOACTIVATE);

    OnFirstTime := False;
    Application.ProcessMessages;

  end;
```

**Comment by mazluta** [comment]
thanks. i will try it
