### ISSUE TITLE
Open/Save Dialog Issues with Right Click Popup Menu

### ISSUE THREAD

**Issue by majorL** [RRUZ/vcl-styles-utils#135]
I am working with XE6 Prof, on Win 10 and themed application.  

Applying the theme to a dialog (open/save), and right clicking on a directory (left panel), or a file (main panel) brings up a popup menu, but the menu items are not displayed correctly (Other then Tortoise SVN).

No issues if I run using standard Windows theme, or if I execute the dialog within the IDE.

**Comment by RRUZ** [comment]
Can you please attach a sample image and a Delphi project to reproduce the issue?

**Comment by majorL** [comment]
Right Clicking on different files/directories produces different popup menus, but all "look" like the attached.

Delphi Project:

program DET;

uses
  Vcl.Forms,
  DETMain in 'DETMain.pas' {Form1},
  Vcl.Themes,
  Vcl.Styles;

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  TStyleManager.TrySetStyle('Carbon');
  Application.CreateForm(TForm1, Form1);
  Application.Run;
end.

unit DETMain;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, Vcl.Styles.Fixes, Vcl.Styles.Hooks;

type
  TForm1 = class(TForm)
    procedure FormCreate(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form1: TForm1;

implementation

{$R *.dfm}

procedure TForm1.FormCreate(Sender: TObject);
var
  od: TOpenDialog;
  fn: String;
begin
  od := TOpenDialog.Create(nil);
  try
    if od.Execute then
       fn := od.FileName;
  finally
    od.Free;
  end;
end;

end.

object Form1: TForm1
  Left = 0
  Top = 0
  Caption = 'Form1'
  ClientHeight = 201
  ClientWidth = 447
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
end

![dialogerror](https://cloud.githubusercontent.com/assets/13647093/9071731/f5861a7e-3ac4-11e5-90c1-aed77d38cfbf.png)

**Comment by RRUZ** [comment]
It seems which in your project some units are missing, try adding those.

  Vcl.Styles.Utils.Graphics
  Vcl.Styles.Hooks
  Vcl.Styles.UxTheme
  Vcl.Styles.Utils.Menus
  Vcl.Styles.Utils.Forms
  Vcl.Styles.Utils.StdCtrls
  Vcl.Styles.Utils.ComCtrls
  Vcl.Styles.Utils.ScreenTips
  Vcl.Styles.Utils.SysControls
  Vcl.Styles.Utils.SysStyleHook

and let me know the results.

**Comment by majorL** [comment]
Yes, Thank you.
