### ISSUE TITLE
TNCButton

### ISSUE THREAD

**Issue by Bononi** [RRUZ/vcl-styles-utils#136]
There is no way to know/set the state of TNCButton, when its style is nsTab, so when creating a set of buttons, the first button is always 'pressed/down'. That makes impossible to save the state or perform the action assigned to that button if you want to make an app where the user wants to keep his last option or set a preferred option. In my app the buttons' style are nsTab and they and the mimic the behavior of a PageControl, and the user could choose to keep his last choice or even set a 'favorite' page to be opened at the application start.

**Comment by RRUZ** [comment]
Thanks for your feedback, please check the new TNCControls.ActiveTabButtonIndex property
