### ISSUE TITLE
VclStylesWebBrowser with TEmbeddedWB?

### ISSUE THREAD

**Issue by PeterPanino** [RRUZ/vcl-styles-utils#138]
Hi! VclStylesWebBrowser seems not working with TEmbeddedWB. How can I make it work?

**Comment by RRUZ** [comment]
Sorry but the *Vcl.Styles.WebBrowser* unit only supports the standard *TWebBrowser*  control.  If you need add support for the *TEmbeddedWB* control you must modify adapt the source code of the [Vcl.Styles.WebBrowser](https://github.com/RRUZ/vcl-styles-utils/blob/master/Common/Vcl.Styles.WebBrowser.pas) unit
