### ISSUE TITLE
Problems with TMS TAdvInputTaskDialogEx

### ISSUE THREAD

**Issue by PeterPanino** [RRUZ/vcl-styles-utils#139]
TAdvInputTaskDialogEx, a Task Dialog wrapper from TMS, did not work well with Amakrits VCL style (see screenshot below). So I tried RRUZ/vcl-styles-utils, and this is what I got:

![snagiteditor 787x426 f074e2c510194d17bbd65e22a7a44118](https://cloud.githubusercontent.com/assets/5140376/9290915/90898492-43a4-11e5-99e4-e881e063549d.png)

You can see that fortunately the vcl-styles-utils made the text inside the dialog white from previous black.

However, the bottom bar now has the "Close Help" text in in almost invisible gray color, and both the OK and Cancel buttons are barely visible. How can improve the colors of the bottom bar?

**Comment by RRUZ** [comment]
You must check the source code of the *TAdvInputTaskDialogEx* component, maybe is not wrapping the [TaskDialog API](https://msdn.microsoft.com/en-us/library/windows/desktop/bb787471(v=vs.85).aspx) and instead is drawing the dialog itself. Anyway you can ask for VCL Styles support to the [component vendor](http://www.tmssoftware.com/site/vtd.asp).
