### ISSUE TITLE
Delphi Tbutton Bug with Styles

### ISSUE THREAD

**Issue by TomTatham** [RRUZ/vcl-styles-utils#140]
In XE7 there is a bug (I reported to EMB) with TButton and styles. If you put two tbuttons on a form and set one of them to Default, when you run the program both buttons are highlighted at the same time if you tab back and forth between them. See  http://stackoverflow.com/questions/31975925/default-button-with-vcl-styles﻿. This wasn't broken in XE2. I have reported the bug to EMB QC. Also, in XE6, there is a different bug related to TButtons. If you put a default tbutton on a form, it loses its highlighted (focused) appearance when you give focus to another control (such as a tedit). I don't know whether there are bugs in XE3-XE5. This completely affects the usability of styles and some of the styled systems dialogs you provide are affected -- depending on which version is used to compile them. Is there some way that you could build a workaround into your code? If not, could you suggest a patch that I could add to the VCL? Thank you!

**Comment by RRUZ** [comment]
I just fixed this issue. Just add the [Vcl.Styles.Fixes](https://github.com/RRUZ/vcl-styles-utils/blob/master/Common/Vcl.Styles.Fixes.pas) unit to your project and register the TButtonStyleHookFix style hook on this way.


```delphi
uses
  Vcl.Styles,
  Vcl.Themes,
  Vcl.Styles.Fixes;

{$R *.dfm}

initialization

TStyleManager.Engine.RegisterStyleHook(TButton, TButtonStyleHookFix);

```

**Comment by TomTatham** [comment]
Thank you! It works great. I am so glad that you are conducting this project.

**Comment by TomTatham** [comment]
I just found a shortcoming to this fix. Specifically, the fix doesn't work if the effect of clicking one of the buttons is to disable itself and the button is subsequently re-enabled through an action that does not involve another button. Both buttons display focused if the remaining enabled button is clicked while the other is disabled. To see this:
1. Style the app (I tested with Luna) and add the fixes as you describe above.
2. Place two tbuttons on the form.
3. Add the following to the onclick handler of button2: button2.enabled := False;
4. Add a ttimer, enable it and add the following to its ontimer event: button2.enabled := True;
5. Run the program, click button 2 and wait for the timer to re-enable it.
6. Click button1. 
Result: Both buttons are highlighted

Thank you!
p.s., I tried uploaed a source code for this but the website would not accept my zip file.

**Comment by RRUZ** [comment]
Please open a new issue to report this, including a sample project. (You can attach a zip file just dropping the file as is explained [here.](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) )

**Comment by jrezalla** [comment]
Hi Guys!

I tried the solution of RRUZ and works. But I am using TBitBtn instead of TButton, and the same problem occurs. I tried the solution ( cl.Styles.Fixes and RegisterStyleHook ) but this solve just for TButton.

Thanks and sorry for my english. :)

**Comment by djjd47130** [comment]
Indeed, I am also using TBitBtn, not TButton. I just had to switch to TButton just to have this fixed.
