### ISSUE TITLE
OpenFolder and Carbon style

### ISSUE THREAD

**Issue by fishMD** [RRUZ/vcl-styles-utils#142]
I have small trouble - when apply Carbon style the text in OpenFolder dialog is black, almost invisible on black background. 
In your demo all working fine. 
I don't write any special code for this. 
Can I change treeview text color in OpenFolder dialog or where is my trouble?

On picture my program on left, and Vcl Styles Utils SysControls (Demo App) right.
<img width="1066" alt="2015-08-29 23 29 33" src="https://cloud.githubusercontent.com/assets/1615198/9564174/f52cc7cc-4ea5-11e5-83a6-d2b1395d54ac.png">

Many thanks!

**Comment by RRUZ** [comment]
Please try adding the Vcl.Styles.Utils.ComCtrls unit to your project.

**Comment by fishMD** [comment]
Don't help. Try add to uses and to project.
Open File show white text color, but Open Folder - black.

**Comment by RRUZ** [comment]
Can you please attach a sample project to reproduce the issue?

**Comment by fishMD** [comment]
I found a solution - add TreeView_SetTextColor(Handle, FontColor); to the end of procedure TSysTreeViewStyleHook.UpdateColors;

**Comment by RRUZ** [comment]
Thanks for your feedback. Check the updated version which fix this issue.
