### ISSUE TITLE
UseLatestCommonDialogs Does not Work

### ISSUE THREAD

**Issue by w2Miller** [RRUZ/vcl-styles-utils#143]
UseLatestCommonDialogs := CheckBoxModernDialogs1.Checked;
When UseLatestCommonDilogs is true and with Vcl.Styles.Utils.SysControls in uses, the TOpenDialog is themed, but the old style XP dialog with a "places panel" on the left side of the dialog is shown.  The latest common dialog is not used.

I understand that  Vcl.Styles.Utils.SysControls or some your code has been incorporated into Delphi 10 Seattle, but even so, Delphi 10 Seattle does not display the latest common TOpenDialog with themes applied to the project.

uses Vcl.Styles.Utils.SysControls, Vcl.Styles.Utils.SystemMenu;

procedure TForm1.Button1Click(Sender: TObject);
begin
  if OpenDialog1.Execute then
  begin
    UseLatestCommonDialogs := True;
    ShowMessage(Format('%s', [OpenDialog1.FileName]));
  end;
end;

In my testing, I can only get the correct latestcommondialog with theming by running your demo project.  All of my tests with my own simple projects with the above code displays a themed old style XP dialog even when UseLatestCommonDialogs is true with Delphi 10 Seattle.

Many of your demo projects have a lot of code in the dpr.  What is the minimum amount of code necessary in the dpr to get correctly themed TOpenDialog with the LatestCommonDialogs with Delphi 10 Seattle?

Update:
Added Vcl.Styles.Utils.ComCtrls, to uses and now latest common dialog is used correctly, but part of the dialog is themed incorrectly.
![image](https://cloud.githubusercontent.com/assets/14111818/9663477/a124ff4c-5232-11e5-9a7d-45b9c55f006f.png)

The big questions are why doesn't TOpenDialog show as a correctly themed modern dialog with 10 Seattle and why does your demo seem to work correctly when any other project I have tried with Vcl.Styles.Utils does not.  I have researched your demos project (dpr) source and the code in your demo but I can not determine what is causing the problem.  Is the problem in the dfm?

Delphi Version: Delphi 10 Seattle
Operating System: Windows 10

Thank-you
Bill

**Comment by RRUZ** [comment]
It seems a issue related to the Enable High-DPI option  in the manifest.

Try disabling that option in the project and let me know the results.

![highdpi](https://cloud.githubusercontent.com/assets/11446959/9676542/bc76a2a2-52a3-11e5-8de6-376ae0164ec3.png)

**Comment by RRUZ** [comment]
I just added support for the VCL Styles when the Enable High DPI option is checked. Try the new version.

**Comment by w2Miller** [comment]
With Delphi 10 Seattle when Enable High-DPI option checked and without Vcl.Styles.Utils.ComCtrls, Vcl.Styles.Utils.SysControls in uses, the dialog still is not themed correctly and still shows the oldstyledialog.

With Delphi 10 Seattle when Enable High-DPI option checked and with Vcl.Styles.Utils.ComCtrls, Vcl.Styles.Utils.SysControls in uses, the dialog is themed correctly and shows the newstyledialog.

**Comment by RRUZ** [comment]
The _Vcl.Styles.Utils.ComCtrls_ unit is always required, please check this wiki page   https://github.com/RRUZ/vcl-styles-utils/wiki/VclStylesSysControls

**Comment by w2Miller** [comment]
I think there is still a small problem.  The shellbreadcrumbbar vertical scrollbar is not themed.
uses
Vcl.FileCtrl,
Vcl.Themes,
Vcl.Styles.Hooks,
Vcl.Styles.Utils.Menus, //Style Popup and Shell Menus (class #32768)
Vcl.Styles.Utils.Forms, //Style dilaogs box (class #32770)
Vcl.Styles.Utils.StdCtrls, //Style buttons, static, and so on
Vcl.Styles.Utils.ComCtrls, //Style SysTreeView32, SysListView32
Vcl.Styles.Utils.ScreenTips, //Style the tooltips_class32 class
Vcl.Styles.Utils.SysControls,
Vcl.Styles.Utils.SysStyleHook,
Vcl.Styles.Utils.SystemMenu;
Enable High-DPI option checked 

procedure TForm1.FormCreate(Sender: TObject);
var
  iVclStylesSystemMenu : TVclStylesSystemMenu;
begin
  iVclStylesSystemMenu:=TVclStylesSystemMenu.Create(Self);
  iVclStylesSystemMenu.MenuCaption:='Choose a VCL Style';
  UseLatestCommonDialogs := True;
end;

See the screenshot.

Bill
![screenshot](https://cloud.githubusercontent.com/assets/14111818/9706472/8c14692a-54b3-11e5-90a4-438fd9633bc1.jpg)

**Comment by RRUZ** [comment]
Thanks Bill, I just created a new issue for this particular case https://github.com/RRUZ/vcl-styles-utils/issues/147 

Rodrigo.
