### ISSUE TITLE
Windows10 Blue style with vcl-styles-utils and TMS TAdvTaskDialogEx

### ISSUE THREAD

**Issue by PeterPanino** [RRUZ/vcl-styles-utils#145]
When using the "Windows10 Blue" Premium Style which comes as a bonus from Embarcadero with Delphi 10 Seattle in Delphi 10 Seattle with vcl-styles-utils I get this result with TMS TAdvTaskDialogEx 1.8.8.0:

![vclstyleswindows10blue](https://cloud.githubusercontent.com/assets/5140376/9699269/d3998dc0-53dc-11e5-9d3c-55f67634c40d.png)

Is there a way to fix this?

**Comment by RRUZ** [comment]
Sorry but this project doesn't support this component. You must ask to the vendor for the VCL Styles support.

**Comment by PeterPanino** [comment]
But the same happens with the TTaskDialog component which
    is from Embarcadero!
    
    Please reopen this issue.
    
    Kind regards,
    Peter
    
    Am 05.09.2015 um 16:31 schrieb Rodrigo
      Ruz:
    
    
      Sorry but this project doesn't support this component. You must
        ask to the vendor for the VCL Styles support.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by RRUZ** [comment]
Hi Peter, On this report you only mention the _TAdvTaskDialogEx _, So  if you have an issue with the _TTaskDialog_  component please open a new issue including a image and  a sample project to reproduce the bug also indicating the Delphi and the Windows version.
