### ISSUE TITLE
Windows10 Blue style with vcl-styles-utils and TTaskDialog

### ISSUE THREAD

**Issue by PeterPanino** [RRUZ/vcl-styles-utils#146]
When using the "Windows10 Blue" Premium Style which comes as a bonus from Embarcadero with Delphi 10 Seattle in Delphi 10 Seattle with vcl-styles-utils I get this result with TTaskDialog:

![image](https://cloud.githubusercontent.com/assets/5140376/9703683/5467288c-548b-11e5-844a-ef36f44cd747.png)

IDE: Delphi 10 Seattle
OS: Windows 7 x64 SP1

**Comment by RRUZ** [comment]
It seems a issue related to the Enable High-DPI option in the manifest.

Try disabling that option in the project and let me know the results.

![](https://cloud.githubusercontent.com/assets/11446959/9676542/bc76a2a2-52a3-11e5-8de6-376ae0164ec3.png)

**Comment by PeterPanino** [comment]
I've disabled it. Unfortunately, it does not help:

![image](https://cloud.githubusercontent.com/assets/5140376/9705434/cd023096-54c4-11e5-91b2-7e2de172b546.png)

**Comment by RRUZ** [comment]
Can you please attach a sample project to reproduce the issue.

**Comment by PeterPanino** [comment]
How can I attach it? ZIP files are not allowed.

**Comment by RRUZ** [comment]
You can use dropbox or send me a mail to rodrigo.ruz.v AT gmail.com

**Comment by PeterPanino** [comment]
OK. I've sent it via email.

**Comment by RRUZ** [comment]
Try the new updated version of the library.

**Comment by PeterPanino** [comment]
Rodrigo, you are so GREAT!!! Now the bug is fixed:

![image](https://cloud.githubusercontent.com/assets/5140376/9706482/a6d473ee-54e6-11e5-89d2-042092c418bd.png)

How did you do this? However, the black font color of TTaskDialog Text is barely visible on the blue background. How can I change it to a more lighter color?

**Comment by RRUZ** [comment]
I just updated the colors used to draw some themed elements.  Try the new updated version of the library.

![2015-09-07 22_32_40-greenshot](https://cloud.githubusercontent.com/assets/11446959/9724929/171b90d2-55b5-11e5-9ae9-985bb31a232b.png)
