### ISSUE TITLE
Toolbar 2000 "black" items background

### ISSUE THREAD

**Issue by dec** [RRUZ/vcl-styles-utils#150]
Hello Rodrigo,

I am begin use your fantastic VCL-Style-Utils library and evertying works fine except I get a problem with the Toolbar 2000 components. Yes; I know this components (developed by Jordan Russel, the Inno Setup author) are a bit old, but offer useful features and in fact works like a charm in many aspects.

The components looks so well when we use an VCL style, except for the toolbar and popmenu items background, which always remains "black". Maybe you can give me some idea in order to solve this problem, maybe some possible "hook" or something like that.

Below you can see what I say in two screenshots, the first shown some toolbar items, the second one shown the popup items:

![screenone](https://cloud.githubusercontent.com/assets/21943/9976959/6aeccd9e-5ef6-11e5-847f-38a89498ccfd.png)

![screentwo](https://cloud.githubusercontent.com/assets/21943/9976958/6ae8661e-5ef6-11e5-8915-978c537b5f33.png)

Hope you can help me and anyway thanks so much for VCL-Style-Utils!

**Comment by dec** [comment]
OMG! Amazing. Just when I send this issue, start to found a possible workaround for the problem in more deep, and, in the "TB2Item.pas" unit of the Toolbar 2000 components, I found this:

{x$DEFINE TB2K_USE_STRICT_O2K_MENU_STYLE}
  { Enabling the above define forces it to use clBtnFace for the menu color
    instead of clMenu, and disables the use of flat menu borders on Windows
    XP with themes enabled. 

Without surprise, I remove the "x" and bing! Now the menus and popup menus appear in the right way using the established VCL style.

Sorry for waste your time Rodrigo, remove this issue if you wanted, or leave it in order to other possible mate.

Thanks anyway and again many thanks for your work at VCl-Styles-Utils libary!

**Comment by RRUZ** [comment]
Gracias David por tus palabras,  que bueno que encontraras las respuesta tu mismo.

Saludos.

**Comment by dec** [comment]
¡Siempre gracias a ti Rodrigo!
