### ISSUE TITLE
TButton.StyleElement not supported

### ISSUE THREAD

**Issue by marikar17** [RRUZ/vcl-styles-utils#152]
The button that the seClient has been removed from the StyleElement is displayed with the background color the selected theme when it should not.

Try this project, just change path in Button.StyleElement.dpr

----------------------------------------------------------------------------------------------------------------
Button.StyleElement.Dpr
--------------------------------
program Button.StyleElement;

uses
  Vcl.Forms,
  MainForm in 'MainForm.pas' {Main},
  Vcl.Themes,
  Vcl.Styles,
  Vcl.Styles.Utils.ComCtrls in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.Utils.ComCtrls.pas',
  Vcl.Styles.Ext in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.Ext.pas',
  Vcl.Styles.Utils.Forms in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.Utils.Forms.pas',
  Vcl.Styles.Utils.Menus in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.Utils.Menus.pas',
  Vcl.Styles.Utils.ScreenTips in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.Utils.ScreenTips.pas',
  Vcl.Styles.Utils.StdCtrls in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.Utils.StdCtrls.pas',
  Vcl.Styles.Utils.SysControls in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.Utils.SysControls.pas',
  Vcl.Styles.Utils.SysStyleHook in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.Utils.SysStyleHook.pas',
  Vcl.Styles.FormStyleHooks in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.FormStyleHooks.pas',
  Vcl.Styles.Utils.Graphics in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.Utils.Graphics.pas',
  DDetours in 'D:\red\vcl-styles-utils.git\trunk\Common\delphi-detours-library\DDetours.pas',
  InstDecode in 'D:\red\vcl-styles-utils.git\trunk\Common\delphi-detours-library\InstDecode.pas',
  Vcl.Styles.UxTheme in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.UxTheme.pas',
  Vcl.Styles.Hooks in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.Hooks.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  TStyleManager.TrySetStyle('Amakrits');
  Application.CreateForm(TMain, Main);
  Application.Run;
end.

----------------------------------------
MainForm.pas
----------------------------------------
unit MainForm;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, Vcl.StdCtrls;

type
  TMain = class(TForm)
    Button1: TButton;
    Button2: TButton;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Main: TMain;

implementation

{$R *.dfm}

end.

----------------------------------------
MainForm.dfm
----------------------------------------
object Main: TMain
  Left = 0
  Top = 0
  Caption = 'Button StyleElement'
  ClientHeight = 90
  ClientWidth = 287
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Button1: TButton
    Left = 20
    Top = 14
    Width = 251
    Height = 25
    Caption = 'seClient in StyleElement'
    TabOrder = 0
  end
  object Button2: TButton
    Left = 20
    Top = 45
    Width = 251
    Height = 25
    Caption = 'seClient not in StyleElement'
    TabOrder = 1
    StyleElements = [seFont, seBorder]
  end
end

------------------------------------------------------------------------------------------------------------------------

To view pure Delphi vcl theme, remove this lines on Button.StyleElement.Dpr

  Vcl.Styles.Utils.ComCtrls in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.Utils.ComCtrls.pas',
  Vcl.Styles.Ext in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.Ext.pas',
  Vcl.Styles.Utils.Forms in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.Utils.Forms.pas',
  Vcl.Styles.Utils.Menus in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.Utils.Menus.pas',
  Vcl.Styles.Utils.ScreenTips in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.Utils.ScreenTips.pas',
  Vcl.Styles.Utils.StdCtrls in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.Utils.StdCtrls.pas',
  Vcl.Styles.Utils.SysControls in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.Utils.SysControls.pas',
  Vcl.Styles.Utils.SysStyleHook in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.Utils.SysStyleHook.pas',
  Vcl.Styles.FormStyleHooks in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.FormStyleHooks.pas',
  Vcl.Styles.Utils.Graphics in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.Utils.Graphics.pas',
  DDetours in 'D:\red\vcl-styles-utils.git\trunk\Common\delphi-detours-library\DDetours.pas',
  InstDecode in 'D:\red\vcl-styles-utils.git\trunk\Common\delphi-detours-library\InstDecode.pas',
  Vcl.Styles.UxTheme in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.UxTheme.pas',
  Vcl.Styles.Hooks in 'D:\red\vcl-styles-utils.git\trunk\Common\Vcl.Styles.Hooks.pas';

Best regards

**Comment by RRUZ** [comment]
Some parts of the library are not compatible with the *StyleElement* property,  As workaround you must follow these steps.

1. Check out the last version of the library.
2. Remove the *Vcl.Styles.UxTheme* unit of your project.
3. Comment the line *{$DEFINE HOOK_UXTHEME}* of  the file *VCL.Styles.Utils.inc*  and save the changes to the file.

Note : If you remove the *Vcl.Styles.UxTheme*  unit of your project you will loose the support for the [modern dialogs](https://github.com/RRUZ/vcl-styles-utils/wiki/VclStylesSysControls). and [Task Dialogs](https://github.com/RRUZ/vcl-styles-utils/wiki/VCLStylesUxTheme).
