### ISSUE TITLE
Style on DevExpress

### ISSUE THREAD

**Issue by francesco76ita** [RRUZ/vcl-styles-utils#154]
Hi, I'm developing with DevExpress VCL 15.1.5. I've some problems applying styles to Cxgrid. 
I know that DevExpress in not compatible with vcl.styles, but I have to make it, and your library
works pretty good. 

In 1.png you can see applied styles to dbgrid, cxgrid (not native) and cxgrid (native). My questions are 

1) Why do only the last column's header doesn't change color? 
2) Why do the scrollbar is still with white background? 

The second problem come at first run, then, if the change style button is pressed and the style is reassigned, the scrollbar take the right color. 
I'm investigating your code and the DevEx's one, but I couldn't find where change your code.
Can you help me to understand ?

Thanks in advance.

Francesco.
![1](https://cloud.githubusercontent.com/assets/14098835/11143234/f3743300-89f3-11e5-9fd4-f192970d66b8.png)

**Comment by RRUZ** [comment]
Francesco, very sorry but my time is very limited (for that reason  support for commercial components is out of the scope of this project.) and add VCL Styles support for the DevExpress TCxGrid components will require a lot of time.
