### ISSUE TITLE
fonts not used for TButton

### ISSUE THREAD

**Issue by Dave-Novo** [RRUZ/vcl-styles-utils#155]
Hello,
I was wondering if you noticed that the VCL Style has a whole series of fonts called ButtonTextXXX that are simply not used by TButton. The Button Style Hook simply uses the font that is set on the button. Is that something that you have fixed?

**Comment by RRUZ** [comment]
As you noted  the *VCL Styles* Engine ignores the fonts types and font size defined in the style file (The font used by the *VCL Styles* is *Tahoma* and the Size is 8). and just use the font color value to draw the text of the controls. Unfortunately add support for custom fonts to the *VCL Styles* requires a lot of work and is out of the scope of this project for now.

**Comment by Dave-Novo** [comment]
Thanks for the prompt response. Since I wrote the post I did some digging in the source and completely agree its a lot of work. FWIW I did put in a feature request with EMB for this....
