### ISSUE TITLE
Range check error when opening OpenDialog

### ISSUE THREAD

**Issue by HPvR** [RRUZ/vcl-styles-utils#158]
Using XE5, and the OpenDialog I am getting range check errors just before the opendialog window opens.  Note that these error reports are not always occuring and are triggered in Design Time only.  Runtime gives no issues 

![image](https://cloud.githubusercontent.com/assets/15804847/11508929/85798c08-985b-11e5-9213-c68d822178fe.png)

Using the 'break' button shows the following location.

![image](https://cloud.githubusercontent.com/assets/15804847/11508963/b04b38dc-985b-11e5-8c35-da8984f980b9.png)

Finally, after closing the program, FASTMM reports the following:
![image](https://cloud.githubusercontent.com/assets/15804847/11508981/cad6141a-985b-11e5-900b-4542eca672f7.png)

The project was originally started using Delphi 5 and was upgraded to XE5 last year.

**Comment by RRUZ** [comment]
Please attach a sample project to reproduce the issue.

**Comment by HPvR** [comment]
This may be a problem inside my program after all.  I am getting exactly the same error report when I remove RegisterSysStyleHook(WC_TABCONTROL, TSysTabControlStyleHook) from the Vcl.Styles.Utils.ComCtrls unit and try to open the help file

![image](https://cloud.githubusercontent.com/assets/15804847/11534540/84b4a82a-990f-11e5-86a3-0acb759165d8.png)

I will try to zoom in on the problem and send you a further update once I can.

**Comment by RRUZ** [comment]
Hi, Any news about this?

**Comment by HPvR** [comment]
Hi Rodrigo,

No news for now due to lack of time.  I will close this issue until I am able to provide you with a simple test program showing the same issue.
