### ISSUE TITLE
TMainMenu - SubMenuImages

### ISSUE THREAD

**Issue by vandrovnik** [RRUZ/vcl-styles-utils#160]
In MainMenu, it is possible to set SubMenuImages. Unfortunatelly, this setting is ignored when using VCL Styles.

**Comment by RRUZ** [comment]
Please attach a sample project to reproduce the issue.

**Comment by vandrovnik** [comment]
Here it is...
[Test5a.zip](https://github.com/RRUZ/vcl-styles-utils/files/58029/Test5a.zip)
[Test5.zip](https://github.com/RRUZ/vcl-styles-utils/files/58030/Test5.zip)
