### ISSUE TITLE
Main menu - items in submenu are not properly aligned

### ISSUE THREAD

**Issue by vandrovnik** [RRUZ/vcl-styles-utils#162]
In submenu, items with and without an image are not aligned - please see attached screenshot.
![mainmenu](https://cloud.githubusercontent.com/assets/13199524/11667615/1adefffc-9df3-11e5-8808-d274d1bb8acb.png)

**Comment by vandrovnik** [comment]
Thank you for fast reaction. In the example application, menu looks all right now, but there is still a (smaller) missalignment in our real application. I am attaching another example.
![test5b](https://cloud.githubusercontent.com/assets/13199524/11776472/b368360a-a247-11e5-9019-84ca7a6f0b0b.png)
[Test5b.zip](https://github.com/RRUZ/vcl-styles-utils/files/60955/Test5b.zip)

**Comment by RRUZ** [comment]
I just fixed the issue, please check the new version.

**Comment by vandrovnik** [comment]
Now it is perfect, thank you very much! :-)
