### ISSUE TITLE
Main menu - keyboard shortcuts are not underlined in sub menu

### ISSUE THREAD

**Issue by vandrovnik** [RRUZ/vcl-styles-utils#163]
In sub menu items, there are shortcut letters defined (&Test - "T" is a shortcut key). Withous styles, when user opens a submenu by keyboard (pressing Alt+F for "&File", for example), he/she sees underlined letters in sub menu items (&Test). When VCL styles is active, these letters in sub menu items are not underlined.

**Comment by RRUZ** [comment]
Please attach a sample project to reproduce the issue.

**Comment by vandrovnik** [comment]
Here it is - Test4.zip contains everything, Test4a.zip source only.
[Test4a.zip](https://github.com/RRUZ/vcl-styles-utils/files/58025/Test4a.zip)
[Test4.ZIP](https://github.com/RRUZ/vcl-styles-utils/files/58026/Test4.ZIP)

**Comment by TomTatham** [comment]
Is this an issue that is likely to be fixed? I am assessing whether to use TMainMenu and this issue is an important factor in the decision. Thank you!

**Comment by RRUZ** [comment]
I hope fix this soon, In fact, I started to work to fix this issue some time ago, But my time is very limited and this issue require a lot of work to get fixed.

**Comment by gandf** [comment]
Maybe commit on my fork [baed8f7ff488e1f1e7bef95dfc8c8d184fcc3810](https://github.com/gandf/vcl-styles-utils/commit/baed8f7ff488e1f1e7bef95dfc8c8d184fcc3810) resolve this issue?

**Comment by RRUZ** [comment]
This issue was fixed in the last commit.
