### ISSUE TITLE
3rd Party Spinedits and vcl.styles.utils.comctrls

### ISSUE THREAD

**Issue by TomTatham** [RRUZ/vcl-styles-utils#166]
I would like to be able to use either tmsadvspinedit (tmssoftware) or tjvspinedit (project jedi) in a styled application. Both components display properly when the application is styled, unless I have also included  vcl.styles.utils.comctrls. Both components display very strange up/down arrows when  vcl.styles.utils.comctrls is included. Is there a workaround to prevent this from happening?

**Comment by RRUZ** [comment]
Please attach a sample image of the *TJvSpinEdit* control styled with the * Vcl.Styles.Utils.ComCtrls* unit. Also which VCL Style are you using?

**Comment by TomTatham** [comment]
Things are more complicated than I realized. The JVSpinedit does not style correctly regardless of whether vcl.styles.utils.comctrls is used. Advspinedit styles correctly without vcl.styles.utils.comctrls but malfunctions when the unit is included.

**Comment by TomTatham** [comment]
![with](https://cloud.githubusercontent.com/assets/13920288/11781625/1aebf0b4-a239-11e5-9dfa-7c6c621b84d5.PNG)
![without](https://cloud.githubusercontent.com/assets/13920288/11781626/1aee9904-a239-11e5-9995-5c31c5f48c70.PNG)

**Comment by RRUZ** [comment]
The issue related to the *JVCL* components must be reported on the [project site](https://github.com/project-jedi/jvcl).  The issue related to the *TAdvSpinEdit* component was fixed, please check out the new version.
