### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by carlosib** [RRUZ/vcl-styles-utils#169]
Hello!

I have this problem:

![draw](https://cloud.githubusercontent.com/assets/14793055/11900513/948d78f0-a58d-11e5-9092-265b5f042cc2.png)

I am using Delphi XE7 + Win 7.

**Comment by RRUZ** [comment]
Please include  a sample project to reproduce the issue.

**Comment by carlosib** [comment]
Hello!

I tried to add Sample.ZIP to this issue but, I have this error:

'Unfortunately, we don’t support that file type.  Escolher arquivos Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.'. Why?

**Comment by RRUZ** [comment]
Maybe is related to the content of your file, Try  using dropbox or [mega](https://mega.nz/),

**Comment by carlosib** [comment]
Hello!
Please, url to download of sample:
http://agenda.eti.br/Sample.ZIP

**Comment by RRUZ** [comment]
I downloaded your sample code but I can't reproduce your issue (Tested on W7 and W10)

![selectfolder](https://cloud.githubusercontent.com/assets/11446959/11941410/20b43e04-a80e-11e5-8b15-fabf263d43c8.png)

And just for curiosity why you are using custom code to show the select folder dialog and not just use the the *SelectDirectory* method of the *Vcl.FileCtrl* unit? try using this method and let me know the results.

**Comment by carlosib** [comment]
Hello!

See, please, http://agenda.eti.br/Sample2.rar .

I have issue only Win7 64bits.

**Comment by RRUZ** [comment]
Can you confirm is you are using the Windows Classic Theme?

**Comment by carlosib** [comment]
Yes. Using Windows Classic Theme no have this issue.

**Comment by RRUZ** [comment]
I'm Sorry, but the library doesn't support the styling of some elements under Windows Classic Theme.
