### ISSUE TITLE
SelectDir without Windows Classic Theme issue.

### ISSUE THREAD

**Issue by carlosib** [RRUZ/vcl-styles-utils#170]
I have this issue:

![sem titulo](https://cloud.githubusercontent.com/assets/14793055/12038336/511d58c4-ae3e-11e5-939b-725d5554f9b0.png)

I have this issue only using Windows 7. Windows 10 works correctly.

**Comment by RRUZ** [comment]
How I said on the issue #169 the library doesn't fully support the styling of some elements under Windows Classic Theme. Also this will not fixed on futures releases because Microsoft deprecated the *Windows Classic Theme* since Windows 8.0.
