### ISSUE TITLE
aero themes

### ISSUE THREAD

**Issue by carlosib** [RRUZ/vcl-styles-utils#171]
Hello!

Sorry again!

I enable 'aero themes' but I have same issue.

![sem titulo](https://cloud.githubusercontent.com/assets/14793055/12043611/d9b68686-ae6d-11e5-92c7-79c1090708d8.png)

Did you reproduced the problem?

I tested with enable themas and disabe themas Windows service.

**Comment by RRUZ** [comment]
In the previous issue you report a problem with the *scrollbar* control not styled. That was only reproducible for me using the *Windows Classic Theme* (which is not supported by this library). Now what is the issue?

**Comment by carlosib** [comment]
Please, select a folder to hint text 'Date created ...' appear as hint over button 'Make Nes Folder', or 'ok' or 'cancel'.
Did you understand?

**Comment by RRUZ** [comment]
I can't reproduce what do you describe , the hint (tooltip windows) appears corrrectly. 

![hint](https://cloud.githubusercontent.com/assets/11446959/12055957/d50c43f2-af10-11e5-8029-470d0283cb5c.png)

As workaround you can disable the hints (tooltips) of the treeview control using the *[TVS_NOTOOLTIPS](https://msdn.microsoft.com/en-us/library/windows/desktop/bb760013(v=vs.85).aspx)*  Style.
