### ISSUE TITLE
Select folder (again)

### ISSUE THREAD

**Issue by carlosib** [RRUZ/vcl-styles-utils#172]
Hello!

See, please, this image: 
![draw](https://cloud.githubusercontent.com/assets/14793055/12092229/e1ab14c8-b2e2-11e5-84c9-ec38f457190c.png)

I believe be problem of this unit:
Vcl.Styles.Utils.ComCtrls.pas

**Comment by RRUZ** [comment]
Hi, do you read my answer on the issue #171 ? "....As workaround you can disable the hints (tooltips) of the treeview control using the TVS_NOTOOLTIPS Style."

**Comment by carlosib** [comment]
But if user try to move window 'select folder' I have same issue.

**Comment by RRUZ** [comment]
But, are you disabling the hints on the *Treeview* Control?

**Comment by carlosib** [comment]
I did other things:
I commented this line:

File: Vcl.Styles.Utils.ComCtrls.pas

with TSysStyleManager do
begin
...
//  RegisterSysStyleHook(WC_TREEVIEW, TSysTreeViewStyleHook);
...
end;

![draw](https://cloud.githubusercontent.com/assets/14793055/12092533/c6c60580-b2e4-11e5-919d-e351b328c840.png)

Sorry, but did you understand?

**Comment by RRUZ** [comment]
That is wrong, what are you doing is disabling the *VCL Style hook* on the control. What I tell you is use the  *TVS_NOTOOLTIPS* style to disable the hint window. please read the MSN documentation https://msdn.microsoft.com/en-us/library/windows/desktop/bb760013(v=vs.85).aspx

**Comment by carlosib** [comment]
Ok.
How I can to do this?
TVS_NOTOOLTIPS (disable?)

**Comment by carlosib** [comment]
I disable tooltips so:

procedure TSysTreeViewStyleHook.UpdateColors;
begin
  SetWindowLong(Handle, GWL_STYLE, GetWindowLong(Handle, GWL_STYLE) or TVS_NOTOOLTIPS);
  inherited;
  if OverrideEraseBkgnd then
    Color := StyleServices.GetStyleColor(scTreeView)
  else
    Color := clWhite;

  if OverrideFont then
    FontColor := StyleServices.GetSystemColor(clWindowText)
  else
    FontColor := clWindowText;
end;

But, when I 'drag' this windows I have this:

![draw](https://cloud.githubusercontent.com/assets/14793055/12093572/ec63207e-b2ea-11e5-8d2d-4f708c685758.png)

**Comment by carlosib** [comment]
Hello!

I fixed so:

procedure TSysTreeViewStyleHook.UpdateColors;
begin
  inherited;
  if OverrideEraseBkgnd then
    Color := StyleServices.GetStyleColor(scTreeView)
  else
    Color := clWhite;

  if OverrideFont then
    FontColor := StyleServices.GetSystemColor(clWindowText)
  else
    FontColor := clWindowText;
  //I added this line: 
  Application.ProcessMessages;
end;

Now works fine using Windows 7.
