### ISSUE TITLE
Some errors when create style with more height on forms title bars

### ISSUE THREAD

**Issue by RicardoBer** [RRUZ/vcl-styles-utils#173]
I found some problems when change one style form title bar size, I modify default style (vsf) and change forms image, this time the title bar has 50px height.

In the attached image.

1.- This zone in tab nc buttons doesn't work on click at all (I think it gets heigh from system variable).

2+3.- If use align on sys buttons, the code create a full 5px height hot zone, yo can click 10px below close button and fire close app, for example. The only thing that seems to correct that behavior it's put align on RightTop, but in this case have another collateral effect and not rearrange well the buttons.
![sin titulo](https://cloud.githubusercontent.com/assets/14173576/12254981/36ce4d6e-b8ef-11e5-8468-06d9162686e7.jpg)

**Comment by RicardoBer** [comment]
On maximize has one more problem, it seems as if the form has more size than screen and cuts title buttons.
![sin titulo](https://cloud.githubusercontent.com/assets/14173576/12255062/f1c77212-b8ef-11e5-94ca-fbe6f42d6b51.jpg)

**Comment by RRUZ** [comment]
Please attach her modified VCL Style file and  your Delphi Version.

**Comment by RicardoBer** [comment]
Wow, super fast response, thanks, many thanks.

Ok, I use RAD Studio XE7 Version 21.0.17707.5020, with update 1.

I see one of the problems (point 1 of first comment) is not a code problem, it's a compiler problem, some times Delphi show me an exception, and after that the problem arise. I can reproduce it some minutes ago, sorry for not to see before.

The other problems are.

In your demos, NC controls, no modifications at all, and when you click maximize system button (maximize application in general). The application not draw correct size and title bar buttons are clipped. It only occurs when include NC library and create NC buttons.

![img_20160112_190732](https://cloud.githubusercontent.com/assets/14173576/12272449/d97aa1e0-b960-11e5-841b-25ff4c6b88bc.jpg)

The other problems are on modify a vsf file and make title bar highest height, I took this same demo, and try on FrmButtonsTabsStyle, load on demo.dpr.

"
if TStyleManager.IsValidStyle('.\MiEstilo.vsf') then
      TStyleManager.LoadFromFile('.\MiEstilo.vsf');
TStyleManager.TrySetStyle('Untitled');
"

), I only change your default load of styles to fit my XE7 structure and add a button on the tabs form (no effect at all).

![sin titulo](https://cloud.githubusercontent.com/assets/14173576/12272554/5d84cc36-b961-11e5-8501-c4526ee74a86.jpg)

Well, the problems that I detect are.

1.- When you click in this area you must be able to move the form, but no work. If you try in other application without styles applied you can see the correct behavior.

2.- Sorry about this, it is related to any problem with compiler, not yours.

3.- When you make your caption bar more tall, if left buttons aligment to saRight, then the buttons are vertical centered, and the left space on top and bottom of them gets clicks to the button, not the title bar. If you change this to saTopRight. that seems better at first glance (not correct position on minimize button), you have buttons at top, left the bottom area under buttons for title bar, but wen the system behavior hide some button the left ones not get correct place. I think this is vcl style delphi problem, not your, but... I'm not sure

Thank again, sorry my poor english and this brick. If I can try something or help in any way, please, contact me.

The Modified Style
[MiEstilo.zip.txt](https://github.com/RRUZ/vcl-styles-utils/files/87790/MiEstilo.zip.txt)

The comment system don't let me upload zip file, I don't not why, download and remove .txt part please

**Comment by RicardoBer** [comment]
More tests. NC Controls oversize on maximized state works ok on Windows XP and Windows 7 32 bits. Fails on Windows 7 64 bits

**Comment by RRUZ** [comment]
Hi Ricardo, I just fixed most of the problems reported here. Some issues are still  present because are related to the *VCL Styles* and you custom VCL Style file. So please try the new version of the library and if you found an issue related to this library open a new issue, please remember report only one problem by issue.
