### ISSUE TITLE
Delphi XE5 with VCL styles, Server 2008 

### ISSUE THREAD

**Issue by greatwood** [RRUZ/vcl-styles-utils#174]
Hiya

I have recently added VCL styles to my app and the ActionMainMenuBar1 component fonts went real small... I found your excellent fix and all works well except... On Windows Server 2008 (and we mostly use this platform to host our app) The text in the main menu is invisible! although the flyouts/drop downs work well with the defined larger font... On Server 2012 and of course on a local Windows PC all works well... But we have to be able to have our app on 2008 for the foreseeable future... Is there anything that you can suggest? I have a little app that displays the behaviour if it would help.

Thanks

Glenn

**Comment by RRUZ** [comment]
Please attach a minimal sample App to reproduce the issue.

**Comment by greatwood** [comment]
Hi This has been done, both a small app and the Delphi code

Thanks
[Menu Gone.zip](https://github.com/RRUZ/vcl-styles-utils/files/94791/Menu.Gone.zip)

**Comment by greatwood** [comment]
If you run the project.exe and hold your mouse over the top menu you'll see the fly out options but no text on the main menu... This behavior is only evident if you run the app on a 2008 server I believe. Running on a 2012 server all is well.

**Comment by greatwood** [comment]
Thanks Rodrigo this has been done

Thanks

Regards

Glenn Greatwood
Key-Data Systems
Director
Signature

**Comment by RRUZ** [comment]
Hi the issue was caused by the Windows Classic Theme. I just updated the [Vcl.PlatformVclStylesActnCtrls](https://github.com/RRUZ/vcl-styles-utils/blob/master/Common/Vcl.PlatformVclStylesActnCtrls.pas) unit (use that unit in your project).

**Comment by greatwood** [comment]
Nice one Rodrigo!

I can confirm that all is working wonderfully now. Many thanks again for 
the unit and your help regarding this

Regards

Glenn Greatwood
Key-Data Systems
Director
Signature
