### ISSUE TITLE
Awesome icons

### ISSUE THREAD

**Issue by Bononi** [RRUZ/vcl-styles-utils#176]
Is there a way to use the awesome icons that we can use in the NC buttons in other components ? I'm developing an app and I would like to keep a clean visual and use the same icons and images in all buttons.

**Comment by RRUZ** [comment]
Hi, yes you can use it, just add the *Vcl.Styles.Utils.Graphics* unit to your project and use the *TAwesomeFont* class via the *AwesomeFont* global variable to draw the icons.
