### ISSUE TITLE
Close button disappear on Finished page when mouse over

### ISSUE THREAD

**Issue by nolme** [RRUZ/vcl-styles-utils#180]
At the end of install, if we move the mouse on the close button on top right corner, it disappear.

Sample code : 
_
#define VclInstallPath   "C:\Program Files (x86)\The Road To Delphi\VCL Styles Inno"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppName=TEST
AppVersion=1.0.0.0
AppVerName=1.0.0.0
DefaultDirName={pf}\Test
  
[Files]
Source: {#VclInstallPath}\VclStylesinno.dll; DestDir: {app}; Flags: dontcopy
Source: {#VclInstallPath}\Styles\Amakrits.vsf; DestDir: {app}; Flags: dontcopy
 
[Code]
// Import the LoadVCLStyle function from VclStylesInno.DLL
procedure LoadVCLStyle(VClStyleFile: String); external 'LoadVCLStyleW@files:VclStylesInno.dll stdcall';
// Import the UnLoadVCLStyles function from VclStylesInno.DLL
procedure UnLoadVCLStyles; external 'UnLoadVCLStyles@files:VclStylesInno.dll stdcall';
 
function InitializeSetup(): Boolean;
begin
  ExtractTemporaryFile('Amakrits.vsf');
  LoadVCLStyle(ExpandConstant('{tmp}\Amakrits.vsf'));
  Result := True;
end;
 
procedure DeinitializeSetup();
begin
  UnLoadVCLStyles;
end;
_

**Comment by RRUZ** [comment]
This issue is not part of this project.
