### ISSUE TITLE
MainMenu -- Images always enabled

### ISSUE THREAD

**Issue by TomTatham** [RRUZ/vcl-styles-utils#183]
When a TMainMenu TMenuItem has an image, the image is always displayed as enabled even when the menu item is disabled. I have tried including VCL.Styles.Utils.Menus but the problem persists. Is this an unfixed issue or are there other units I need to include?

**Comment by RRUZ** [comment]
Please attach a sample project to reproduce the issue.

**Comment by TomTatham** [comment]
This sample project is self-explanatory: [TMainmenu Disabled Image Bug.zip](https://github.com/RRUZ/vcl-styles-utils/files/253978/TMainmenu.Disabled.Image.Bug.zip)

**Comment by RRUZ** [comment]
Thanks for report this, I just fixed the issue. So now you can add the _Vcl.Styles.Utils.Menus_ unit to your project.

**Comment by TomTatham** [comment]
Thank you so much! This really gets me out of a jam; due to some incompatibilities between a docking system I am using and tactionmainmenubar, I really need to be able to use tmainmenu. I really appreciate how quickly you resolved this, too. 
Best wishes,
Tom
On May 8, 2016 22:20, Rodrigo Ruz <notifications@github.com> wrote:Thanks for report this, I just fixed the issue. So now you can add the Vcl.Styles.Utils.Menus unit to your project.
