### ISSUE TITLE
Delphi 10.1 Berlin

### ISSUE THREAD

**Issue by gynngr** [RRUZ/vcl-styles-utils#184]
I cannot compile f.e. TThemedMenuItemHelper.GetPaintRect, because Delphi no longer allows access to private fields via class helper. Do you plan to implement access via rtti ?

**Comment by RRUZ** [comment]
Hi, I just added support for RAD Studio 10.1 Berlin. Try the new version of the library.

**Comment by gynngr** [comment]
@RRUZ, thank you for the changes in unit Vcl.PlatformVclStylesActnCtrls and some others.
Unfortunately there are many other units, which I have to compile.

In the meantime I changed all units using rtti at least for read access and raise expections when write access is execute, so for my duty all is fine now.

I thing it's better to uses rtti like 

``` pascal
function TThemedMenuItemHelper.GetPaintRect: TRect;
begin
  Result := TRttiContext.Create.GetType(Self.ClassType).GetField('FPaintRect').GetValue(Self).AsType<TRect>;
  // Result := Self.FPaintRect;
end;
```
 or
``` pascal
class function TCustomStyleEngineHelper.GetRegisteredStyleHooks: TStyleHookDictionary;
begin
  Result := TRttiContext.Create.GetType(Self).GetField('FRegisteredStyleHooks').GetValue(Self).AsType<TStyleHookDictionary>;
  // Result := Self.FRegisteredStyleHooks;
end;
```
instead of shadow classes
``` pascal
function TThemedMenuItemHelper.GetPaintRect: TRect;
begin
 {$IF (CompilerVersion <31))}
 Result := Self.FPaintRect;
 {$ELSE}
  Result := TShadowClassThemedMenuItem(Self).FPaintRect;
 {$IFEND}
end;
```
or fixed offset access
``` pascal
class function TCustomStyleEngineHelper.GetRegisteredStyleHooks: TStyleHookDictionary;
var
  p : Pointer;
begin
  {$IF (CompilerVersion <31)}
  Result:= Self.FRegisteredStyleHooks;
  {$ELSE}
   {
   TCustomStyleEngine.FRegisteredStyleHooks:
   00651030 3052AA           xor [edx-$56],dl
   00651033 02F7             add dh,bh
   00651035 097623           or [esi+$23],esi
   TCustomStyleEngine.$ClassInitFlag:
   00651038 FFFF             db $ff $ff
   0065103A FFFF             db $ff $ff
   TCustomStyleEngine.FRegSysStylesList:
   0065103C D037             shl [edi],1
    }
  {$IFDEF CPUX64}
   p      := Pointer(PByte(@Self.FRegSysStylesList) - 24);
  {$ELSE}
   p      := Pointer(PByte(@Self.FRegSysStylesList) - 12);
  {$ENDIF CPUX64}
  Result := TStyleHookDictionary(p^);
  {$IFEND}
end;
```
Because I'm not familar with GitHub I can only provide my changes as zip.

[vcl-styles-utils-changes.zip](https://github.com/RRUZ/vcl-styles-utils/files/293748/vcl-styles-utils-changes.zip)

**Comment by RRUZ** [comment]
@gynngr , I don't understand your comment, the full library is compatible with Berlin. Also the code which you attach is a very old version of the library.

**Comment by gynngr** [comment]
@RRUZ, sorry for any inconveniences. Indeed I made this changes on first downloaded version from 2015-02-05. But even with your current version from 2016-05-24 there are problems f.e.
```pascal
function TDbGridHelper.GetIndicators: TImageList;
begin
 Result:=Self.FIndicators; // !! no longer access to private field !!
end;
```
My problem is that -for easy use- I build a package with all your source files and maybe some of them are no longer needed.

Now I reduced the package to Vcl.Styles.Ext and delphi-detours-library, so I can use my favourite TVclStylesPreview and all is fine now.

Thank you for sharing your work :+1:

**Comment by gynngr** [comment]
addendum: 

- TVclStylesPreview.Paint  should be public
- TVclStylesPreviewClass does not exist

```pascal
type
  /// <summary> The <c>TVclStylesPreview</c> class, is a control for display  a preview of any Vcl style loaded
  /// </summary>
  /// <remarks>
  /// sample of use
  /// <code>
  ///   ...
  ///      TVclStylesPreviewClass(FPreview).Paint;<para></para>  ***does not compile***
  ///      FPreview.Paint;<para></para>
  ///   ...
  /// </code>
  /// </remarks>
  TVclStylesPreview = class(TCustomControl)
  private
    ...
  protected
    // procedure Paint; override; ***no access from outside***
  public
    procedure Paint; override;
    property Icon:HICON read FIcon Write FIcon;
    property Style:TCustomStyleServices read FStyle Write FStyle;
    property Caption : TCaption read FCaption write FCaption;
    property BitMap : TBitmap read FBitmap write FBitmap;
    constructor Create(AControl: TComponent); override;
    destructor Destroy; override;
  end;
```
