### ISSUE TITLE
Cannot change TListView group style

### ISSUE THREAD

**Issue by relativ** [RRUZ/vcl-styles-utils#185]
Hello,

I am faceing a trouble, I cant change TListView group color can you help me about this ?

Thanks for this good work.

**Comment by RRUZ** [comment]
Hello, There is not a documented _WinApi_ function to modify the _ListView_ Group color. However you can overcome this limitation adding the [Vcl.Styles.Hook](https://github.com/RRUZ/vcl-styles-utils/blob/master/Common/Vcl.Styles.Hooks.pas) unit to your project.

 Check this sample image

![https://theroadtodelphi.files.wordpress.com/2014/11/2014-11-04-11_12_45-demo.png](https://theroadtodelphi.files.wordpress.com/2014/11/2014-11-04-11_12_45-demo.png)

**Comment by relativ** [comment]
How can I use Vcl.Styles.Hook in my project ? is it enough to import it to the project ?

**Comment by RRUZ** [comment]
Please check the wiki for more info https://github.com/RRUZ/vcl-styles-utils/wiki/VCLStylesHook
