### ISSUE TITLE
MessageBox truncated text

### ISSUE THREAD

**Issue by jsweby** [RRUZ/vcl-styles-utils#187]
The text of a MessageBox API call is truncated when styles are used.

Using your workaround from http://community.embarcadero.com/answers/my-questions/removing-vcl-style-on-the-messages/latest:

TStyleManager.SystemHooks := TStyleManager.SystemHooks - [shDialogs];

for now but of course this removes the style from the message. This cannot be done around every message in the system.

![messagebox_style](https://cloud.githubusercontent.com/assets/20184678/16411791/cd742b5c-3d20-11e6-8064-456c9ccfc03a.png)
![messagebox_nostyle](https://cloud.githubusercontent.com/assets/20184678/16411792/cd76fbca-3d20-11e6-838b-0d3a101c21a5.png)

**Comment by RRUZ** [comment]
I just fixed this issue.

Remember  add these units to your project 

  Vcl.Styles.Utils.Menus, //Style Popup and Shell Menus (class #32768)
  Vcl.Styles.Utils.Forms, //Style dialogs box (class #32770)
  Vcl.Styles.Utils.StdCtrls, //Style buttons, static, and so on
  Vcl.Styles.Utils.ComCtrls, //Style SysTreeView32, SysListView32
  Vcl.Styles.Utils.ScreenTips, //Style the tooltips_class32 class
  Vcl.Styles.Utils.SysControls,
  Vcl.Styles.Utils.SysStyleHook,

**Comment by hristiiann** [comment]
Where exacly these files need to be added? in the plugin's func or at main .nsi?

Thanks
