### ISSUE TITLE
Colored TLabel

### ISSUE THREAD

**Issue by ange007** [RRUZ/vcl-styles-utils#188]
Hello.
How it is possible to realize colored **TLabel** in **Delphi XE10**?

Advice https://stackoverflow.com/questions/9995080/delphi-xe2-vcl-styles-remove-a-style-or-disable-a-class-skinning-from-a-tlabel - not work, and from this library nothing helps unfortunately.

**Comment by RRUZ** [comment]
Hi, the answer which you mention is prior to the introduction of the [StyleElements](http://docwiki.embarcadero.com/Libraries/Berlin/en/Vcl.Controls.TControl.StyleElements) property, So now  all you need to do to preserve the original color of the _TLabel_ is remove the _seFont_ element of the _StyleElements_ property.

**Comment by jsweby** [comment]
Hi, I am having a similar problem but only with the VCL Styles Utils added.

I have a TPanel and a TLabel on which the Color property is set to clInfoBk (not the Font.Color, but the control's Color, to give them a background).

I have unset all elements of the StyleElements property.

With no VCL Style Utils files in the uses clauses, these render correctly.

![no_style_utils](https://cloud.githubusercontent.com/assets/20184678/18201497/74e0b116-7102-11e6-9f43-9137146e0b9c.png)

Once I add Vcl.Styles.Utils.Forms (which I need to render dialogs correctly), it doesn't seem to honour the colours.

![with_style_utils](https://cloud.githubusercontent.com/assets/20184678/18201498/74e19ec8-7102-11e6-900c-08cd73b1c37c.png)

Please can you assist or is this a bug?
