### ISSUE TITLE
Button lose Style on click

### ISSUE THREAD

**Issue by schallerthomas** [RRUZ/vcl-styles-utils#189]
I use your vcl-style-utils to customize my open/save dialog. This works absolutely great.
But the Buttons lose the style after I click on them -> see attached screenshot. Is this a known issue?
![unbenannt](https://cloud.githubusercontent.com/assets/20518304/17510459/4aa6334e-5e1f-11e6-8b70-0cb40c87630b.PNG)

Thanks,
Thomas

**Comment by RRUZ** [comment]
I can't reproduce what you describe. Please attach a basic sample project to reproduce the issue.

**Comment by schallerthomas** [comment]
Thank´s for the fast reply. I´m on holidays the next two weeks and attach a sample afterwards.

**Comment by RRUZ** [comment]
Any news about this issue? do you have the sample project?

**Comment by schallerthomas** [comment]
Please excuse my delay. I had to disable the vcl-style-utils in our programm, because the utils also styles the program in which our programm is running integratet. This is why  i can't  offer you a sample project any more. Please close this issue.
