### ISSUE TITLE
Access violation on starting the application

### ISSUE THREAD

**Issue by luraze** [RRUZ/vcl-styles-utils#190]
I use c++builder 10 Seattle. I get an access violation when I run any VCL application:
![image](https://cloud.githubusercontent.com/assets/12396248/17662626/1c94ef96-62e7-11e6-9e2b-2b389112d4af.png).
This is all the info I get from the debugger. It won't point me to any specific code.

I tried creating a brand new app, with a TListView and TEdit. I added Vcl.Styles.Utils.SysStyleHook.pas to the project. I also tried adding all of the files. Nothing seems to work. Perhaps I need the delphi-part of Rad Studio?

Sorry I can't give you any more information, but this is all I get from the debugger.

Edit: I use Windows 10 pro. It actually work on win64 apps, but not 32.

**Comment by RRUZ** [comment]
Try disabling the option "Link with runtime packages" located in 
Project->Options->Packages->Runtime Packages

**Comment by luraze** [comment]
Hot diggety. That did the trick. Thanks! :)

**Comment by luraze** [comment]
Dang it. Disabling runtime packages also disables the whole theme in other DLLs.
