### ISSUE TITLE
[Request]: LCL Styles Utils (for Lazarus)

### ISSUE THREAD

**Issue by shobits1** [RRUZ/vcl-styles-utils#191]
1. Could you please make VCL(maybe LCL) Styles Utils for Lazarus?
2. if not could you please provides some guide lines onto how can I achieve this.
3. is VCL Styles Utils multi-Platform or windows only?

thanks.

**Comment by RRUZ** [comment]
Hi Check my answers below.

**Could you please make VCL(maybe LCL) Styles Utils for Lazarus?**
  Unfortunately this require a lot of work. Also this is out of the scope of this project. 

 **if not could you please provides some guide lines onto how can I achieve this?**
  You need write from the scratch the skin library. You can use as inspiration the Vcl Styles code included in the source files of RAD Studio. 

**is VCL Styles Utils multi-Platform or windows only?**
 The _VCL Styles Utils_ is only a extension for the VCL Styles (included in RAD Studio) which only work under Windows.
