### ISSUE TITLE
TControl.Color being lost using VCL Styles Utils

### ISSUE THREAD

**Issue by jsweby** [RRUZ/vcl-styles-utils#192]
Hi, I am having a problem that only occurs when the VCL Styles Utils units are added.

I have a TPanel and a TLabel on which the Color property is set to clInfoBk (not the Font.Color, but the control's Color, to give them a background).

I have unset all elements of the StyleElements property.

With no VCL Style Utils files in the uses clauses, these render correctly.

![no_style_utils](https://cloud.githubusercontent.com/assets/20184678/18201497/74e0b116-7102-11e6-9f43-9137146e0b9c.png)

Once I add Vcl.Styles.Utils.Forms (which I need to render dialogs correctly), it doesn't seem to honour the colours.

![with_style_utils](https://cloud.githubusercontent.com/assets/20184678/18201498/74e19ec8-7102-11e6-900c-08cd73b1c37c.png)

If I comment out the line:

`{$DEFINE USE_Vcl.Styles.Hooks}`

from Vcl.Styles.Utils.inc then it works again but I suspect I'm losing other functionality by doing this.

Please can you assist or is this a bug?

**Comment by RRUZ** [comment]
The _Vcl.Styles.Hooks_ unit includes a _detour_ to patch the WinAPI [GetSysColor](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724371(v=vs.85).aspx) method, this function is used internally by the _VCL_ to determine the current system colors. On this case when you uses the  _clInfoBk_ value (COLOR_INFOBK) and the   _Vcl.Styles.Hooks_ unit  the returned value is the _clInfoBk_ but for the current active VCL Style. If you want to get the native system colors the only workround is use the _Trampoline_user32_GetSysColor_  function and set the color in run-time.

Try this sample.

```
uses
 Vcl.Styles.Hooks;

procedure TForm53.FormCreate(Sender: TObject);
begin
  Panel1.Color :=  Trampoline_user32_GetSysColor(COLOR_INFOBK);
  Label1.Color :=  Trampoline_user32_GetSysColor(COLOR_INFOBK);
end;

```

![bkinfo](https://cloud.githubusercontent.com/assets/11446959/18236095/2b13f48c-72f9-11e6-87f8-f3281cbb1436.png)

**Comment by jsweby** [comment]
Thank you. This alerted me to the fact that the clInfoBk syscolor in the VCL Style was actually a grey background, so I changed this back to the standard Windows pale-yellow colour. I also cleared the StyleElements property of the TPanel.
