### ISSUE TITLE
Non-Client Area - overlap form icon

### ISSUE THREAD

**Issue by djjd47130** [RRUZ/vcl-styles-utils#193]
I'm trying to use the TNCControls to place a button in the far upper-left corner of the form, in place of the form's icon, just like almost all new Windows 10 apps do. However, when I do so, clicking in the area still clicks the form icon, instead of the button. I've tried numerous things, but to no avail...

1. Replaced the form's Icon with a completely empty .ico file.
2. Changing form style to bsSizeToolWin, but the title bar becomes too small, and I lose the minimize / maximize buttons.
3. Changing form style to bsDialog, but I get the same effect as #2 above, as well as not being able to resize the form.
4. Made sure button style is nsPushButton, and although it covers up the form icon, clicking the area still clicks the icon, which in turn shows the default system menu.
5. Following [everything in this thread](https://social.msdn.microsoft.com/Forums/en-US/099fd9ae-fbf9-4a3c-80de-77c41a123662/windows-api-removing-icon-from-windows-title-bar-without-removing-system-menu?forum=vcgeneral), but the conclusion is that Windows forces you to have this icon.

Currently, I'm forced to place this button just to the right of the form icon. But how can I properly completely overlap this icon to remove its default functionality?

**Comment by RRUZ** [comment]
The `TNCControls` component includes the `ShowSystemMenu` property. If you set the value to false, then the system menu will be not shown.

Try this


```
    uses
     Vcl.Styles.Utils.Graphics;
    
    procedure TfrmTestMain.FormCreate(Sender: TObject);
    begin
     SetupTitleBar;
    end;
    
    procedure TfrmTestMain.NCClick(Sender: TObject);
    begin
      ShowMessage('Hello');
    end;
    
    procedure TfrmTestMain.SetupTitleBar;
    var
      B: TNCButton;
    begin
      FNCControls:= TNCControls.Create(Self);
      FNCControls.ShowSystemMenu := False; //Disable the system menu.
    
      B := FNCControls.ButtonsList.Add;
      B.Style := TNCButton.TNCButtonStyle.nsTranparent;
      B.BoundsRect := Rect(0, 0, 45, 32);
      B.UseFontAwesome:= True;
      B.Caption := '';
      B.ImageAlignment:= TImageAlignment.iaCenter;
      B.ImageStyle:= TNCButton.TNCImageStyle.isNormal;
      B.ImageIndex:= fa_chevron_left;
      B.OnClick := NCClick;
    end;
```
