### ISSUE TITLE
TRichEdit Hook don't work in Berlin 10.1

### ISSUE THREAD

**Issue by amigage** [RRUZ/vcl-styles-utils#197]
Hello,

I've tested your demo "Vcl Styles Hooks" in Delphi Berlin 10.1.
The problem is that the SelAttributes.Color don't work. The color remains white...

Please, could you check it ?

Best regards
Amigage

**Comment by RRUZ** [comment]
Try the last version.

**Comment by amigage** [comment]
Hello,

many thanks for the update, but the problem still appears if you change the color of a selected text in TRichEdit.

Please check the following in your example "Vcl Styles Hooks".

procedure TFrmMain.ColorBox1Change(Sender: TObject);
begin
  RichEdit1.SelAttributes.Color := ColorBox1.Color;
end;

If you change the color, the selected text will be white...

Regards
Amigage

**Comment by RRUZ** [comment]
You need to remove the _seFont_ element of the _StyleElements_ property of the RichEdit control.  I just updated the demo App with this change.

**Comment by amigage** [comment]
Thanks for the hint. Now it works. Thumbs up ;-)
