### ISSUE TITLE
Finding Styled Tab colors

### ISSUE THREAD

**Issue by bdwilton** [RRUZ/vcl-styles-utils#198]
Hi RRUZ,

I was wondering if you could give me some insight in finding out what colors a tab has been assigned eg nromal, hot, and pressed.

I was trying -
var LThemedTab: TThemedTab;
...
LThemedTab := ttTabItemNormal;
LDetails := StyleServices.GetElementDetails(LThemedTab);
StyleServices.GetElementColor(LDetails, ecFillColor, LNormalColor);
StyleServices.GetElementColor(LDetails, ecTextColor, LFontNormalColor);

These are the standard VCL theme function, in the above ecTextColor I think is producing a valid value but ecFillColor is not loaded for tabs.

Would there be a mechnism with your Vcl.Style.Ext.pas to figure out what the tab colors are ?

**Comment by RRUZ** [comment]
Unfortunately you can't get the colors of the tabs used because these are drawn using the bitmap linked to the current element (_ttTabItemSelected_, _ttTabItemHot_, _ttTabItemNormal_), Only the text color of the tabs can be retrieved by using the _GetElementColor_.
