### ISSUE TITLE
Selected ListView items are black if HotTrackStyles.htUnderlineHot is activated

### ISSUE THREAD

**Issue by amigage** [RRUZ/vcl-styles-utils#199]
Hello,

I'm again with a small issue. The problem is described in the subject.

Open your VCL Styles Hooks Demo and for the Listview activate the HotTrackStyles option htUnderlineHot.
Now if you select an item it will be painted completely black.

I used this option before, but my software can also be used without this option :-)

**Comment by RRUZ** [comment]
Thanks for this report. I just fixed this. Please check the new version.
