### ISSUE TITLE
Visual artifacts in Delphi VCL Styles

### ISSUE THREAD

**Issue by nickolasdeluca** [RRUZ/vcl-styles-utils#200]
I currently have my application running on Windows 10.
And I like to set the "Windows10Dark" VCL Style in delphi, the application looks alot more eye friendly.
But I've began to notice that there are a lot of visual artifacts when it I use the TFileOpenDialog component.
(In my application I need to get the file path of folders selected by the user, so the TFileOpenDialog is necessary since OpenDialog doesnt have support for selecting folders).
vcl-styles-utils already corrected a huge amount of visual artifacts when it comes to this component, but still, the Windows10Dark VCL Style still requires some refinement...
I'm attaching a print bellow just so you can see what I'm talking about, pay attention to the file path edit...

![sem titulo](https://cloud.githubusercontent.com/assets/17858166/23714437/dd87a7a4-0407-11e7-8969-98d5b3309c5d.png)

**Comment by RRUZ** [comment]
To avoid the artifacts you must activate the styling of the dialogs following the instructions from here 

https://github.com/RRUZ/vcl-styles-utils/wiki/VclStylesSysControls

**Comment by nickolasdeluca** [comment]
Already did that, the problem continues...
UseLatestCommonDialogs was set to True and all those units were already added to the uses list.
(I'm sorry, I didnt mention it before)

**Comment by RRUZ** [comment]
Ok, then please attach a basic sample project to reproduce the issue.

**Comment by nickolasdeluca** [comment]
Here you go:
[Demo.zip](https://github.com/RRUZ/vcl-styles-utils/files/828756/Demo.zip)

**Comment by nickolasdeluca** [comment]
Just in case this is a relevant information...
My current OS build is:
Edition: Windows 10 Enterprise
Version: 1607
OS Build: 14393.953

**Comment by RRUZ** [comment]
Thanks for this report, I just uploaded a new version which fix the issue related to the artifacts in the Windows 10 Custom Styles.

![hover black](https://cloud.githubusercontent.com/assets/11446959/24434953/e5287c34-1408-11e7-9cae-ef4f9ecc4fa1.png)
![w10](https://cloud.githubusercontent.com/assets/11446959/24434955/e7082c34-1408-11e7-8bf5-e14e0ff77273.png)
![blue](https://cloud.githubusercontent.com/assets/11446959/24434958/e96e00ca-1408-11e7-83af-b14e9af1b004.png)

**Comment by nickolasdeluca** [comment]
Thank you so much, I was really looking forward to this fix.
