### ISSUE TITLE
TrackBar selection is not shown. 

### ISSUE THREAD

**Issue by AlexGrigg** [RRUZ/vcl-styles-utils#201]
TTrackBar has properties for selection (SelStart and SelEnd). 
![default](https://cloud.githubusercontent.com/assets/26464092/24003774/71cf6abe-0a75-11e7-8901-8c2faf634027.png)
The selection isn’t shown with style.

**Comment by RRUZ** [comment]
Hi, I just uploaded this bug to Embarcadero.

https://quality.embarcadero.com/browse/RSP-17806.
