### ISSUE TITLE
App won't start in W10 RS2

### ISSUE THREAD

**Issue by Himeko7** [RRUZ/vcl-styles-utils#204]
There seems to be an issue with the VCL Styles units and the upcoming RS2 build of Windows 10, the app won't start at all if you include the units.

```
  Vcl.Styles.Ext,
  Vcl.Styles.Utils,
  Vcl.Styles.Hooks,
  Vcl.Styles.Utils.Menus, //Style Popup and Shell Menus (class #32768)
  Vcl.Styles.Utils.Forms, //Style dilaogs box (class #32770)
  Vcl.Styles.Utils.StdCtrls, //Style buttons, static, and so on
  Vcl.Styles.Utils.ComCtrls, //Style SysTreeView32, SysListView32
  Vcl.Styles.Utils.ScreenTips, //Style the tooltips_class32 class
  Vcl.Styles.Utils.SysControls,
  Vcl.Styles.Utils.SysStyleHook,
```

**Comment by woodie2** [comment]
same problem here with 'Windows 10 Creators Update'

**Comment by Himeko7** [comment]
Do you think this can be fixed before the release on April 11th?

**Comment by KarlheinzJansen** [comment]
I have also a problem under Win 10 Creators Update and with Delphi 10.1 Upd2  in 
function Detour_UxTheme_OpenThemeDataForDPI(hwnd: HWND; pszClassList: LPCWSTR; hwnd2: HWND): HTHEME; stdcall;
 line    THThemesClasses.Add(Result, pszClassList);
Before it jumps into the line:  Result = 0; pszClassList = ''

The error occurs WITHOUT any compatibility settings,
 but DOES NOT occur with the compatibility setting to Windows 7.
In mode Windows 7 for the EXE the programm does not jump into this function. 
In normal mode it jumps into the function.

Maybe it is same issue.

**Comment by RRUZ** [comment]
Thanks for the info, I will check this ASAP.

**Comment by RRUZ** [comment]
I just added a fix. please update your copy of the library.

**Comment by KarlheinzJansen** [comment]
Thank you Rodriguez, my issue is solved.
By the way, can you also update the Detours library to the actual one?

**Comment by Himeko7** [comment]
Perfect, that fixed it. Thank you.
