### ISSUE TITLE
Checkbox "losing" the theme

### ISSUE THREAD

**Issue by CleitonLuanGiehl** [RRUZ/vcl-styles-utils#206]
Hi there, i'm here to report the case when i set a theme (Windows10.vsf) and the checkboxe's of the page "wpSelectTasks" are showed normal themed on de fist time the page has showed, but when i do a "Next" and a "Back" the stiles is retored to default windows theme like that:

![print1](https://cloud.githubusercontent.com/assets/29204567/26788831/d65cb24e-49e4-11e7-8c52-779603c04e4d.png)

![print2](https://cloud.githubusercontent.com/assets/29204567/26788842/e01cfb7c-49e4-11e7-81af-5b6f26811181.png)

I need to manual call a function on a page change to force the theme?

Tanks!

**Comment by RRUZ** [comment]
This issue belongs to the Vcl Styles Plugins project https://github.com/RRUZ/vcl-styles-plugins/issues
