### ISSUE TITLE
Crash in Vcl.Styles.Utils.SysStyleHook

### ISSUE THREAD

**Issue by luebbe** [RRUZ/vcl-styles-utils#209]
Hi Rodrigo,

I'm trying to activate the styling for Commondialogs as in your example. 
Environment: Delphi 10.1 Berlin, Windows 32.

Whenever I activate any of Vcl.Styles.Utils.ComCtrls, or .StdCtrls and open a FileOpen/Save Dialog, an `ERangeError` exception occurs at the line `hFont := SendMessage(Handle, WM_GETFONT, 0, 0);` in Vcl.Styles.Utils.SysStyleHook.

```delphi
function TSysControl.GetFont: TFont;
var
  LogFont: TLogFont;
  hFont: HGDIOBJ;
begin
  if FFont <> nil then
    Exit(FFont);

  hFont := SendMessage(Handle, WM_GETFONT, 0, 0);
  Result := TFont.Create;
  FillChar(LogFont, SizeOf(LogFont), 0);
  GetObject(hFont, SizeOf(LogFont), @LogFont);
  Result.Name := StrPas(LogFont.lffaceName);

```

This is the top part of the call stack:
```
:7798dbe8 KERNELBASE.RaiseException + 0x48
Vcl.Styles.Utils.SysStyleHook.TSysControl.GetFont
Vcl.Styles.Utils.SysStyleHook.TSysControl.GetFont
Vcl.Styles.Utils.StdCtrls.TSysStaticStyleHook.Paint($B6A5720)
Vcl.Styles.Utils.SysStyleHook.TSysStyleHook.WMPaint((15, 0, 0, 0, 0, 0, (), 0, 0, (), 0, 0, ()))
Vcl.Styles.Utils.SysStyleHook.TSysStyleHook.WndProc((15, 0, 0, 0, 0, 0, (), 0, 0, (), 0, 0, ()))
Vcl.Styles.Utils.StdCtrls.TSysStaticStyleHook.WndProc((15, 0, 0, 0, 0, 0, (), 0, 0, (), 0, 0, ()))
:004da22a StdWndProc + $16
:768384f3 user32.SetManipulationInputTarget + 0x53
:76816c40 ; C:\Windows\SysWOW64\user32.dll
:76816820 ; C:\Windows\SysWOW64\user32.dll
:7681d169 ; C:\Windows\SysWOW64\user32.dll
:77cc8e56 ntdll.KiUserCallbackDispatcher + 0x36
:76829af0 ; C:\Windows\SysWOW64\user32.dll
:76829804 ; C:\Windows\SysWOW64\user32.dll
:768296f2 user32.DialogBoxIndirectParamAorW + 0x32
:768296ab user32.DialogBoxIndirectParamW + 0x1b
:7515144c ; C:\Windows\SysWOW64\comdlg32.dll
:005f5e13 TCustomFileDialog.Execute + $373
:005f3304 TFileDialogWrapper.Execute + $19C
:005f3f95 TOpenDialog.DoExecute + $105
:005f3e20 TOpenDialog.Execute + $14

```
my uses list currently looks like this. When I uncomment any of the two lines, the exception occurs. Does the order of including the units play a role?
```
  ...
  Vcl.Themes,
  Vcl.Styles,
//  Vcl.Styles.Utils.ComCtrls in '..\..\Packages\vcl-styles-utils\Common\Vcl.Styles.Utils.ComCtrls.pas',
  Vcl.Styles.Utils.Forms in '..\..\Packages\vcl-styles-utils\Common\Vcl.Styles.Utils.Forms.pas',
  Vcl.Styles.Utils.Menus in '..\..\Packages\vcl-styles-utils\Common\Vcl.Styles.Utils.Menus.pas',
  Vcl.Styles.Utils.ScreenTips in '..\..\Packages\vcl-styles-utils\Common\Vcl.Styles.Utils.ScreenTips.pas',
//  Vcl.Styles.Utils.StdCtrls in '..\..\Packages\vcl-styles-utils\Common\Vcl.Styles.Utils.StdCtrls.pas',
  Vcl.Styles.Utils.SysControls in '..\..\Packages\vcl-styles-utils\Common\Vcl.Styles.Utils.SysControls.pas',
  Vcl.Styles.Utils.SysStyleHook in '..\..\Packages\vcl-styles-utils\Common\Vcl.Styles.Utils.SysStyleHook.pas',
  Vcl.Styles.Hooks in '..\..\Packages\vcl-styles-utils\Common\Vcl.Styles.Hooks.pas',
  DDetours in '..\..\Packages\vcl-styles-utils\Common\delphi-detours-library\DDetours.pas',
  InstDecode in '..\..\Packages\vcl-styles-utils\Common\delphi-detours-library\InstDecode.pas',
```

I could not narrow it down any further until now.

**Comment by AdminUser0** [comment]
I think this is a similar report:
https://stackoverflow.com/questions/45919887/error-when-using-vcl-themes-on-a-promptforfilename-dialog

**Comment by luebbe** [comment]
Hi Rodrigo,
I'm still stuck with this problem and haven't found a solution for it. I managed to strip down my test application so that it crashes reliably when vcl.styles.utils.comctrls and/or vcl.styles.utils.stdctrls are included in the .dpr file.
Can I make it available to you via dropbox?

**Comment by luebbe** [comment]
The try..except in GetFont just delays the crash (in most cases).
The next exception occurs in `procedure TSysTreeViewStyleHook.WndProc(var Message: TMessage);`
line `TreeView_SetBkColor(Handle, ColorToRGB(Color));`

**Comment by prognase** [comment]
Same issue for me under Tokyo 10.2.2. Am a new user trying to use VCL-Style-Utils, have the problem under 32bit and 64bit. TFileOpenDialog is crashing, TOpenTextFileDialog works fine.

Have not a lot of experience with VCL styles, will try to get more info / code around this. An update to this to make it work for supplied dialogs is much appreciated.

**Comment by rickard67** [comment]
Change the line
hFont := SendMessage(Handle, WM_GETFONT, 0, 0);

to

hFont := HGDIOBJ(SendMessage(Handle, WM_GETFONT, 0, 0));

That should solve the range check issue.

**Comment by prognase** [comment]
Very nice: made the change, compiled a project, ran a couple of times and clicked around, mostly using system dialogs - no crashes. Thanks a lot!
