### ISSUE TITLE
TListview Checkboxes are not drawn correctly

### ISSUE THREAD

**Issue by luebbe** [RRUZ/vcl-styles-utils#211]
Hi Folks,

we have a problem with checkboxes in TListView (vsReport), that are not drawn correctly when one of our custom styles is used. The bitmap(s) for checkboxes in this style are 15x15 pixel, 
Normal checkboxes are drawn correctly in 15x15px. The checkboxes in the TListView only have 13x13 and are drawn inconsistently. The checked ones are properly centered, but cut off to fit into 13x13. The unchecked ones show a small border at the right side which look like it is part of the "checked" bitmap.

See attached screenshot, yellow highlight by me.

We are using vcl.styles.hooks plus some other units from vcl-styles-utils. The listview is not ownerdrawn

I'm trying to find out whether:
- It's a bug in our custom style
- It's a bug in vcl.styles
- It's a bug in vcl.styles.hooks

Any pointers how we can fix this problem? I would be happy already if the unchecked checkbox didn't have the blue right border, even happier if the checkboxes would be drawn in the correct size with the complete bitmap.

Cheers & thanks

![tlistviewcheckboxproblem](https://user-images.githubusercontent.com/3872576/29412102-a271eac4-8357-11e7-830c-97181b9946c6.png)

**Comment by RRUZ** [comment]
Hello, the checkboxes of the _TListView_ are styled hooking the _Uxtheme_ directly (https://github.com/RRUZ/vcl-styles-utils/blob/master/Common/Vcl.Styles.UxTheme.pas#L1903). The bounds of the checkbox are determined by the system, So you can change these. As workaround you can try modifying the code  to draw a scaled version of the bitmap.

**Comment by luebbe** [comment]
Thanks for the pointer. I'll continue from there.
