### ISSUE TITLE
TDBCheckBox and TDBCtrlGrid

### ISSUE THREAD

**Issue by theazgra** [RRUZ/vcl-styles-utils#214]
When using TDBCheckBox on TDBCtrlgrid, with TABSTable there is a bug.

When selected row is changed (dataset scrolled), value from previous row is copied into every other row or atleast all checkboxes have same visuals (all are checked or vice verse).

If seClient is removed from checkbox's StyleElements this behavior is fixed, but only checkbox in selected row is visible. As seen on images below.
Is there fix for this?

![grid1](https://user-images.githubusercontent.com/18343952/30708587-b4d3af22-9eff-11e7-969a-fbe8ab52f131.png)
![grid2](https://user-images.githubusercontent.com/18343952/30708588-b4da3270-9eff-11e7-8291-bbc0d595b6bf.png)

**Comment by RRUZ** [comment]
This looks like a bug in the VCL Styles (and not on this project), you should report this to _Embarcadero_.
