### ISSUE TITLE
Missing unit Vcl.SysStyles

### ISSUE THREAD

**Issue by ThomasJaeger** [RRUZ/vcl-styles-utils#215]
Hi, I'm using Delphi XE4 and just cloned the latest code. I can not compile my app now and getting the following error:

[dcc32 Fatal Error] Vcl.Styles.Utils.ScreenTips.pas(57): F1026 File not found: 'Vcl.SysStyles.dcu'

Where do I get this unit? Thanks!

**Comment by RRUZ** [comment]
Thanks Thomas for the report.  I just fixed this.
