### ISSUE TITLE
vcl-styles-utils & Synedit

### ISSUE THREAD

**Issue by GrooverMD** [RRUZ/vcl-styles-utils#220]
Rodrigo,

Awesome library. I followed your instructions to skin the scroll bars on a Synedit component 

    TStyleManager.Engine.RegisterStyleHook( TCustomSynEdit, TMemoStyleHook ); 

but I have an issue with the Synedit component flickering when horizontal scroll is used. Without the hook there is no problem, with the hook the problem arises. Is there a workaround for this as the Synedit component does not have a double buffer property?

**Comment by pyscripter** [comment]
Try
`
  TStyleManager.Engine.RegisterStyleHook(TCustomSynEdit, TScrollingStyleHook);
`
and manually fix font and color.

**Comment by GrooverMD** [comment]
Thanks for the prompt response. Yes that worked.
Cheers.
