### ISSUE TITLE
Problems with drawing system dialog boxes after the last update of Windows 10

### ISSUE THREAD

**Issue by flutomax** [RRUZ/vcl-styles-utils#249]
After a recent recent update of Windows 10, artifacts were discovered in the file open/save dialogs.
This is how the file selection dialog box on the computer looks like, where the latest Windows 10 update was not made, see screenshort: 
![sound_art_dialog_box_before_update_windows_10](http://stone-voices.ru/img/scr/sound_art_dialog_box_before_update_windows_10.png)
And this is how the file selection dialog on the computer looks like, where the last update of Windows 10 was made, see screenshort:
![sound_art_dialog_box_after_update_windows_10](http://stone-voices.ru/img/scr/sound_art_dialog_box_after_update_windows_10.png)
Artifacts are noticed when drawing button captions (blur)
Also, TaskMessageDlg has become incorrect to draw the background.

**Comment by flutomax** [comment]
> Tried in both Windows 10 Pro (version 1903 build 18362) and Windows 10 Pro Insider Preview (version 1903 build 18917). I used both dark, light and custom Windows themes, but can't reproduce your issue.
> Open, save and open picture dialogs looks fine.
> 
> I have no idea why it doesn't work properly at your end, but maybe you should experiment a little. Maybe create a test program with buttons to open different shell dialogs (open/save...) and see if you can make it work.
> 
> /Rickard

I tried to make a simple program with a button and a file open dialog. The problem has not disappeared.
My Windows version is 10.0.17134.885.

Without adding modules vcl-styles-utils everything works ok, but I want to apply styles to all elements, including the system elements. In the .dpr file the uses section is typed like this:
uses
  Windows,
  System.IOUtils,
  Types,
  System.SysUtils,
  Vcl.Themes,
  Vcl.Styles,
  Vcl.Forms,
  DDetours,
  InstDecode,
  Vcl.Styles.Hooks,
  Vcl.Styles.UxTheme,
  Vcl.Styles.Utils.Graphics,
  Vcl.Styles.Utils.Menus,
  Vcl.Styles.Utils.Forms,
  Vcl.Styles.Utils.StdCtrls,
  Vcl.Styles.Utils.ComCtrls,
  Vcl.Styles.Utils.ScreenTips,
  Vcl.Styles.Utils.SysControls,
  Vcl.Styles.Utils.SysStyleHook,
  uMain in 'uMain.pas' {Form1};

**Comment by rickard67** [comment]
I tried again using your uses section, but it still looks fine at my end.

1. Are you sure you are using the latest version of vcl-styles-utils ? Personally, I use this one https://github.com/salvadordf/vcl-styles-utils.

2. What happens if you create a simple program and run it on a different computer?
   - If it looks fine on the other computer - you may have an issue with your Windows copy.

Apart from that - I'm not sure I can help much since I can't reproduce it. I use vcl-styles-utils in my main application and from countless users I've never heard anyone seeing this issue...

**Comment by rickard67** [comment]
This may help a little...

https://github.com/RRUZ/vcl-styles-utils/issues/255

**Comment by flutomax** [comment]
After the last update of Windows, the problem ceased to exist. Now everything is displayed correctly.
