### ISSUE TITLE
Vcl.Styles.Ext.pas does not compile with Delphi 10.4 Sydney

### ISSUE THREAD

**Issue by StefanGrube** [RRUZ/vcl-styles-utils#263]
Due to {$DEFINE USE_VCL_STYLESAPI} the include files {$I '..\source\vcl\StyleUtils.inc'} and {$I '..\source\vcl\StyleAPI.inc'} are imported, but cannot be compiled with following error messages:

[dcc32 Fehler] StyleUtils.inc(1110): E2003 Undeklarierter Bezeichner: 'TDirect2DCanvas'
[dcc32 Fehler] StyleUtils.inc(1111): E2003 Undeklarierter Bezeichner: 'ID2D1Bitmap'
[dcc32 Fehler] StyleUtils.inc(1112): E2003 Undeklarierter Bezeichner: 'TD2DRectF'
[dcc32 Fehler] StyleUtils.inc(1144): E2066 Operator oder Semikolon fehlt
[dcc32 Fehler] StyleUtils.inc(1144): E2034 Zu viele Parameter
[dcc32 Fehler] StyleUtils.inc(1146): E2066 Operator oder Semikolon fehlt
[dcc32 Fehler] StyleUtils.inc(1148): E2066 Operator oder Semikolon fehlt
[dcc32 Fehler] StyleUtils.inc(1148): E2010 Inkompatible Typen: 'Integer' und 'TseBitmap'
[dcc32 Fehler] StyleUtils.inc(1149): E2066 Operator oder Semikolon fehlt
[dcc32 Fehler] StyleUtils.inc(1150): E2066 Operator oder Semikolon fehlt
[dcc32 Fehler] StyleUtils.inc(1151): E2066 Operator oder Semikolon fehlt
[dcc32 Fehler] StyleUtils.inc(1152): E2066 Operator oder Semikolon fehlt
[dcc32 Fehler] StyleUtils.inc(1154): E2066 Operator oder Semikolon fehlt
[dcc32 Fehler] StyleUtils.inc(1154): E2066 Operator oder Semikolon fehlt
[dcc32 Fehler] StyleUtils.inc(1155): E2003 Undeklarierter Bezeichner: 'D2D1_BITMAP_INTERPOLATION_MODE_LINEAR'
[dcc32 Fehler] StyleUtils.inc(1157): E2066 Operator oder Semikolon fehlt
[dcc32 Fehler] StyleUtils.inc(1162): E2066 Operator oder Semikolon fehlt
[dcc32 Fehler] StyleAPI.inc(5161): E2003 Undeklarierter Bezeichner: 'EndsText'
[dcc32 Fataler Fehler] VisualStyles.dpk(44): F2063 Verwendete Unit 'Vcl.Styles.Ext.pas' kann nicht compiliert werden

**Comment by StefanGrube** [comment]
All errors could be fixed by adding the following units to the uses clause of Vcl.Styles.Ext.pas:

Uses
  ...
  Vcl.Direct2D,
  Winapi.D2D1,
  System.StrUtils;

**Comment by luebbe** [comment]
Does it still compile with older Delphi versions afterwards? Maybe you need an $ifdef around the uses

**Comment by StefanGrube** [comment]
At least with 10.3 it does compile, I don't have older versions installed.

**Comment by luebbe** [comment]
That's good news.

**Comment by RRUZ** [comment]
Fixed
