### ISSUE TITLE
Latest merges downgraded several files

### ISSUE THREAD

**Issue by salvadordf** [RRUZ/vcl-styles-utils#265]
The commit https://github.com/RRUZ/vcl-styles-utils/commit/f5bcc8d7e796eabaf813ae044267fd254b3f9d38 downgraded the Vcl.Styles.UxTheme.pas unit to the version previous to this commit https://github.com/RRUZ/vcl-styles-utils/commit/ff5a26f0a76a99556ab8dc4ac2d7606b12645233 

Some other files like VCL.Styles.Utils.inc also lost some of the recent changes.

**Comment by RRUZ** [comment]
I just checked the changes made to _Vcl.Styles.UxTheme_   but  only I found one  https://github.com/RRUZ/vcl-styles-utils/commit/f5bcc8d7e796eabaf813ae044267fd254b3f9d38#diff-8ace86092b6909cbdf3ea53c508a329b

**Comment by salvadordf** [comment]
I think there's an issue with GitHub. 

It reports that those files only had minor changes but if you check the real file contents before and after the latest commits you will see different changes.

Just to give an example, the current Vcl.Styles.UxTheme version declares TDrawThemeBackground at line 83 : 
https://github.com/RRUZ/vcl-styles-utils/blob/fa4eb08c83af64906678a31c3783c7e228a3ef52/Common/Vcl.Styles.UxTheme.pas#L83
This is the same file in August 12th, 2019. It declares TDrawThemeBackground at line 154 : 
https://github.com/RRUZ/vcl-styles-utils/blob/ff5a26f0a76a99556ab8dc4ac2d7606b12645233/Common/Vcl.Styles.UxTheme.pas#L154

This is the history of that file : 
https://github.com/RRUZ/vcl-styles-utils/commits/master/Common/Vcl.Styles.UxTheme.pas

Daniel-Tr submitted a PR where he reordered much of the code in that unit in August 12th, 2019 but somewhere along the line that file lost those changes.

Another example is the VCL.Styles.Utils.inc file. This is a much smaller file and it's much easier to see the lost changes.

I submitted a PR that renamed one directive and you merged it ( ¡Muchas gracias! :D ) but the history doesn't show it and the current file has the old directive. This is the history of that file : 
https://github.com/RRUZ/vcl-styles-utils/commits/master/Common/VCL.Styles.Utils.inc
This is the PR : 
https://github.com/RRUZ/vcl-styles-utils/pull/264

**Comment by RRUZ** [comment]
@salvadordf,  can you please create a PR with the changes (this is the fastest way) ? or send me the list of the modified files ( Vcl.Styles.UxTheme.pas,  VCL.Styles.Utils.inc, ...)

**Comment by salvadordf** [comment]
I just created the PR #266 with all the code changes including #264 and #261

**Comment by RRUZ** [comment]
Gracias de nuevo @salvadordf por tus continuos aportes.
