### ISSUE TITLE
Delphi 10.4 VCL styles support, Detours v2.2 and other high DPI issues

### ISSUE THREAD

**Issue by rickard67** [RRUZ/vcl-styles-utils#269]
I've created a temporary download location for the latest version + my own additions. 
It should contain all the latest changes from both the main repository and the Salvador repository.

For more information and download - please follow the link below. You also need v2.2 of the Detours library.
https://www.rj-texted.se/Forum/viewtopic.php?f=22&t=4893

/Rickard

**Comment by RRUZ** [comment]
@rickard67 feel free to create a pull request with your additions to be included in the project,

**Comment by rickard67** [comment]
Done!
