### ISSUE TITLE
Messagedlg bad visual with Alexandria ?

### ISSUE THREAD

**Issue by lchris789** [RRUZ/vcl-styles-utils#292]
I have a strange issue with delphi Alexandria.

Create a blank vcl themed project with any theme active. Lets say "Windows10"

add these units to the mais project dpr file
  Vcl.Themes,
  Vcl.Styles,
  Vcl.Styles.Utils.SysControls,
  Vcl.Styles.ColorTabs,
  Vcl.Styles.UxTheme,
  Vcl.Styles.Utils.Menus,
//  Vcl.Styles.Utils.Forms,
//  Vcl.Styles.Utils.StdCtrls,
//  Vcl.Styles.Utils.ComCtrls,
  Vcl.Styles.Utils.ScreenTips,

and this event in the main form

procedure TForm1.FormClick(Sender: TObject);
begin
   MessageDlg('Hello, This is a messagedlg box size exemple', mtWarning, [mbOK, mbCancel], 0);
end;

run it and clic to  see the messagebox size is OK

Now uncomment one of the 3 uses lines above

run it again and clic to  see the messagebox size is wroongly enlarged !

???? I could not find why this happens.

please help

can someone reproduce this ?

I guess this has something to do with the needed use of DwmGetWindowAttribute
in windows versions above 6 

in Vcl.Styles.Utils.SysStyleHook
function TSysControl.GetWinRect: TRect;
is using only   Winapi.Windows.GetClientRect(Handle, Result);
and this is not enought because shadow is included in the size and needs to be removed

I'm still far from solving this ! where is DwmGetWindowAttribute even declared in delphi ??
EDIT : found in Winapi.DwmApi.pas

Hmm ..; DwmGetWindowAttribute  returns the same size

Could it be that the messagedlg form size is correct but everything inside is wrongly drawn ?

My head is overheating, I need the help of a real ingeneer who likes puzzles.

**Comment by DinuruSeniya** [comment]
I found an interesting fact that in Delphi 11, the TSysControl.GetWinRect method gets called multiple times when a MessageBox is created, 
but in Delphi 10.3 it isn't. It is called only, for example, when creating a 'Save As' or 'Open' file dialog.

**Comment by RRUZ** [comment]
I have fixed this Alexandria issue, please pull and Retest.

**Comment by lchris789** [comment]
Thank you !!! I will try
Good weekend !
