### ISSUE TITLE
Access Violation using TVCLStylesPreview in Alexandria (with solution)

### ISSUE THREAD

**Issue by jdorlon-Quest** [RRUZ/vcl-styles-utils#293]
Running the VCL Styles Preview demo under Delphi 11 Alexandria will result in an access violation.

The solution is to change this, in VCL.Styles.Ext, around line 93

```
  TSourceInfo = record
    Data: TStyleServicesHandle;
    StyleClass: TCustomStyleServicesClass;
  end;
```

to this
```
  TSourceInfo = record
    Data: TStyleServicesHandle;
    StyleClass: TCustomStyleServicesClass;
    DesigningState: Boolean;
  end;
```

**Comment by RRUZ** [comment]
This was fixed at https://github.com/RRUZ/vcl-styles-utils/commit/7171cc231d8eadabba10fbbbd89768a405fc8a69
