### ISSUE TITLE
What fixes/tweaks are still applicable for use with RAD Studio 11 Alexandria?

### ISSUE THREAD

**Issue by darianmiller** [RRUZ/vcl-styles-utils#296]
VCL Style support within RAD Studio has been progressively getting better.  Can you clarify which tweaks/features are still needed/usable in the latest version of RAD Studio?

**Comment by jdorlon-Quest** [comment]
@DinuruSeniya thanks for the info.   I still have VCL Styles Utils compiled in my project, but I no longer have the package installed into Delphi.  I am not working today, but when I get a chance I'll try my project w/o VCL Style Utils and see what happens.  I'll post again when I know something more.

**Comment by jdorlon-Quest** [comment]
Oops, hah, I forgot to post again.   I am on Delphi 11.2 and VCL Style Utils is definitely still needed.   I am also using Dev Express controls.  VCL Style Utils helps theme some of theirs too (but a lot of manual work is also needed with devex)

**Comment by RRUZ** [comment]
@darianmiller   I just fixed some issues related to Alexandria.

About what parts are still applicable: 
   I would say only [Vcl.Styles.Fixes](https://github.com/RRUZ/vcl-styles-utils/wiki/VclStylesFixes), [Vcl.Styles.WebBrowser](https://github.com/RRUZ/vcl-styles-utils/wiki/VclStylesWebBrowser) and Vcl.Styles.Utils.Menus  are currently covered for the VCL Styles- So you can still use the VCL style utils hooks, task dialog support and NC controls in Alexandria,

**Comment by jdorlon-Quest** [comment]
Thank your for the updates, Rodrigo
