### ISSUE TITLE
TTaskDialog styling scale incorrect

### ISSUE THREAD

**Issue by rshuck** [RRUZ/vcl-styles-utils#297]
Using Win11 and Alexandria (don't know about earlier versions) when showing a styled task dialog using the demo application the size of the box is larger than expected which results in an ugly looking bottom and right hand edge.

![image](https://user-images.githubusercontent.com/3933542/162446913-4aeede8e-2dc6-45e9-8aa9-f89c8db6c37f.png)

Whereas the screenshots on the web do not show this.

**Comment by DinuruSeniya** [comment]
Having the same issues when upgrading from D10.3 to D11. This issue wasn't present before. Seems like the Delphi VCL has improved enough that this component is not needed anymore. Plus this component supports Delphi till 10.4 Seattle.

**Comment by DinuruSeniya** [comment]
However, file open/save dialogs still need to be themed with vcl-styles-utils.
Is there a way to disable vcl-styles-utlils for only TTaskDialogs? @salvadordf

**Comment by DinuruSeniya** [comment]
You can update the copyright, but you can't even fix these bugs which makes programs unusable for release with Delphi Alexandria!!! @RRUZ

**Comment by luebbe** [comment]
... and merge Bugfix PRs that are open since more than a year ...
See #288
